# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newlogin.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newLogin(object):
    def setupUi(self, newLogin):
        newLogin.setObjectName("newLogin")
        newLogin.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        newLogin.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(newLogin)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_login = QtWidgets.QPushButton(newLogin)
        self.btn_login.setMinimumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 2, 2, 1, 1)
        self.btn_back = QtWidgets.QPushButton(newLogin)
        self.btn_back.setMinimumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 2, 0, 1, 1)
        self.lbl_title = QtWidgets.QLabel(newLogin)
        self.lbl_title.setMinimumSize(QtCore.QSize(121, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout.addWidget(self.lbl_title, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(487, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(newLogin)
        self.groupBox.setMinimumSize(QtCore.QSize(741, 331))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keyboard = QtWidgets.QFrame(self.groupBox)
        self.keyboard.setMaximumSize(QtCore.QSize(510, 250))
        self.keyboard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keyboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyboard.setObjectName("keyboard")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.keyboard)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.row1 = QtWidgets.QHBoxLayout()
        self.row1.setContentsMargins(11, 11, 11, 11)
        self.row1.setSpacing(6)
        self.row1.setObjectName("row1")
        self.Q = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q.sizePolicy().hasHeightForWidth())
        self.Q.setSizePolicy(sizePolicy)
        self.Q.setMinimumSize(QtCore.QSize(46, 46))
        self.Q.setMaximumSize(QtCore.QSize(46, 46))
        self.Q.setObjectName("Q")
        self.row1.addWidget(self.Q)
        self.W = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.W.sizePolicy().hasHeightForWidth())
        self.W.setSizePolicy(sizePolicy)
        self.W.setMinimumSize(QtCore.QSize(46, 46))
        self.W.setMaximumSize(QtCore.QSize(46, 46))
        self.W.setObjectName("W")
        self.row1.addWidget(self.W)
        self.E = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E.sizePolicy().hasHeightForWidth())
        self.E.setSizePolicy(sizePolicy)
        self.E.setMinimumSize(QtCore.QSize(46, 46))
        self.E.setMaximumSize(QtCore.QSize(46, 46))
        self.E.setObjectName("E")
        self.row1.addWidget(self.E)
        self.R = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R.sizePolicy().hasHeightForWidth())
        self.R.setSizePolicy(sizePolicy)
        self.R.setMinimumSize(QtCore.QSize(46, 46))
        self.R.setMaximumSize(QtCore.QSize(46, 46))
        self.R.setObjectName("R")
        self.row1.addWidget(self.R)
        self.T = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T.sizePolicy().hasHeightForWidth())
        self.T.setSizePolicy(sizePolicy)
        self.T.setMinimumSize(QtCore.QSize(46, 46))
        self.T.setMaximumSize(QtCore.QSize(46, 46))
        self.T.setObjectName("T")
        self.row1.addWidget(self.T)
        self.Y = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y.sizePolicy().hasHeightForWidth())
        self.Y.setSizePolicy(sizePolicy)
        self.Y.setMinimumSize(QtCore.QSize(46, 46))
        self.Y.setMaximumSize(QtCore.QSize(46, 46))
        self.Y.setObjectName("Y")
        self.row1.addWidget(self.Y)
        self.U = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U.sizePolicy().hasHeightForWidth())
        self.U.setSizePolicy(sizePolicy)
        self.U.setMinimumSize(QtCore.QSize(46, 46))
        self.U.setMaximumSize(QtCore.QSize(46, 46))
        self.U.setObjectName("U")
        self.row1.addWidget(self.U)
        self.I = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.I.sizePolicy().hasHeightForWidth())
        self.I.setSizePolicy(sizePolicy)
        self.I.setMinimumSize(QtCore.QSize(46, 46))
        self.I.setMaximumSize(QtCore.QSize(46, 46))
        self.I.setObjectName("I")
        self.row1.addWidget(self.I)
        self.O = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O.sizePolicy().hasHeightForWidth())
        self.O.setSizePolicy(sizePolicy)
        self.O.setMinimumSize(QtCore.QSize(46, 46))
        self.O.setMaximumSize(QtCore.QSize(46, 46))
        self.O.setObjectName("O")
        self.row1.addWidget(self.O)
        self.P = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P.sizePolicy().hasHeightForWidth())
        self.P.setSizePolicy(sizePolicy)
        self.P.setMinimumSize(QtCore.QSize(46, 46))
        self.P.setMaximumSize(QtCore.QSize(46, 46))
        self.P.setObjectName("P")
        self.row1.addWidget(self.P)
        self.verticalLayout.addLayout(self.row1)
        self.row2 = QtWidgets.QHBoxLayout()
        self.row2.setContentsMargins(11, 11, 11, 11)
        self.row2.setSpacing(6)
        self.row2.setObjectName("row2")
        self.A = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A.sizePolicy().hasHeightForWidth())
        self.A.setSizePolicy(sizePolicy)
        self.A.setMinimumSize(QtCore.QSize(46, 46))
        self.A.setMaximumSize(QtCore.QSize(46, 46))
        self.A.setObjectName("A")
        self.row2.addWidget(self.A)
        self.S = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S.sizePolicy().hasHeightForWidth())
        self.S.setSizePolicy(sizePolicy)
        self.S.setMinimumSize(QtCore.QSize(46, 46))
        self.S.setMaximumSize(QtCore.QSize(46, 46))
        self.S.setObjectName("S")
        self.row2.addWidget(self.S)
        self.D = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D.sizePolicy().hasHeightForWidth())
        self.D.setSizePolicy(sizePolicy)
        self.D.setMinimumSize(QtCore.QSize(46, 46))
        self.D.setMaximumSize(QtCore.QSize(46, 46))
        self.D.setObjectName("D")
        self.row2.addWidget(self.D)
        self.F = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F.sizePolicy().hasHeightForWidth())
        self.F.setSizePolicy(sizePolicy)
        self.F.setMinimumSize(QtCore.QSize(46, 46))
        self.F.setMaximumSize(QtCore.QSize(46, 46))
        self.F.setObjectName("F")
        self.row2.addWidget(self.F)
        self.G = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G.sizePolicy().hasHeightForWidth())
        self.G.setSizePolicy(sizePolicy)
        self.G.setMinimumSize(QtCore.QSize(46, 46))
        self.G.setMaximumSize(QtCore.QSize(46, 46))
        self.G.setObjectName("G")
        self.row2.addWidget(self.G)
        self.H = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H.sizePolicy().hasHeightForWidth())
        self.H.setSizePolicy(sizePolicy)
        self.H.setMinimumSize(QtCore.QSize(46, 46))
        self.H.setMaximumSize(QtCore.QSize(46, 46))
        self.H.setObjectName("H")
        self.row2.addWidget(self.H)
        self.J = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.J.sizePolicy().hasHeightForWidth())
        self.J.setSizePolicy(sizePolicy)
        self.J.setMinimumSize(QtCore.QSize(46, 46))
        self.J.setMaximumSize(QtCore.QSize(46, 46))
        self.J.setObjectName("J")
        self.row2.addWidget(self.J)
        self.K = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K.sizePolicy().hasHeightForWidth())
        self.K.setSizePolicy(sizePolicy)
        self.K.setMinimumSize(QtCore.QSize(46, 46))
        self.K.setMaximumSize(QtCore.QSize(46, 46))
        self.K.setObjectName("K")
        self.row2.addWidget(self.K)
        self.L = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L.sizePolicy().hasHeightForWidth())
        self.L.setSizePolicy(sizePolicy)
        self.L.setMinimumSize(QtCore.QSize(46, 46))
        self.L.setMaximumSize(QtCore.QSize(46, 46))
        self.L.setObjectName("L")
        self.row2.addWidget(self.L)
        self.verticalLayout.addLayout(self.row2)
        self.row3 = QtWidgets.QHBoxLayout()
        self.row3.setContentsMargins(11, 11, 11, 11)
        self.row3.setSpacing(6)
        self.row3.setObjectName("row3")
        self.btnShift = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShift.sizePolicy().hasHeightForWidth())
        self.btnShift.setSizePolicy(sizePolicy)
        self.btnShift.setMinimumSize(QtCore.QSize(0, 46))
        self.btnShift.setMaximumSize(QtCore.QSize(49, 46))
        self.btnShift.setObjectName("btnShift")
        self.row3.addWidget(self.btnShift)
        self.Z = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Z.sizePolicy().hasHeightForWidth())
        self.Z.setSizePolicy(sizePolicy)
        self.Z.setMinimumSize(QtCore.QSize(46, 46))
        self.Z.setMaximumSize(QtCore.QSize(46, 46))
        self.Z.setObjectName("Z")
        self.row3.addWidget(self.Z)
        self.X = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X.sizePolicy().hasHeightForWidth())
        self.X.setSizePolicy(sizePolicy)
        self.X.setMinimumSize(QtCore.QSize(46, 46))
        self.X.setMaximumSize(QtCore.QSize(46, 46))
        self.X.setObjectName("X")
        self.row3.addWidget(self.X)
        self.C = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C.sizePolicy().hasHeightForWidth())
        self.C.setSizePolicy(sizePolicy)
        self.C.setMinimumSize(QtCore.QSize(46, 46))
        self.C.setMaximumSize(QtCore.QSize(46, 46))
        self.C.setObjectName("C")
        self.row3.addWidget(self.C)
        self.V = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.V.sizePolicy().hasHeightForWidth())
        self.V.setSizePolicy(sizePolicy)
        self.V.setMinimumSize(QtCore.QSize(46, 46))
        self.V.setMaximumSize(QtCore.QSize(46, 46))
        self.V.setObjectName("V")
        self.row3.addWidget(self.V)
        self.B = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B.sizePolicy().hasHeightForWidth())
        self.B.setSizePolicy(sizePolicy)
        self.B.setMinimumSize(QtCore.QSize(46, 46))
        self.B.setMaximumSize(QtCore.QSize(46, 46))
        self.B.setObjectName("B")
        self.row3.addWidget(self.B)
        self.N = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N.sizePolicy().hasHeightForWidth())
        self.N.setSizePolicy(sizePolicy)
        self.N.setMinimumSize(QtCore.QSize(46, 46))
        self.N.setMaximumSize(QtCore.QSize(46, 46))
        self.N.setObjectName("N")
        self.row3.addWidget(self.N)
        self.M = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M.sizePolicy().hasHeightForWidth())
        self.M.setSizePolicy(sizePolicy)
        self.M.setMinimumSize(QtCore.QSize(46, 46))
        self.M.setMaximumSize(QtCore.QSize(46, 46))
        self.M.setObjectName("M")
        self.row3.addWidget(self.M)
        self.btnDel = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDel.sizePolicy().hasHeightForWidth())
        self.btnDel.setSizePolicy(sizePolicy)
        self.btnDel.setMinimumSize(QtCore.QSize(0, 46))
        self.btnDel.setMaximumSize(QtCore.QSize(49, 46))
        self.btnDel.setObjectName("btnDel")
        self.row3.addWidget(self.btnDel)
        self.verticalLayout.addLayout(self.row3)
        self.row4 = QtWidgets.QHBoxLayout()
        self.row4.setContentsMargins(11, 11, 11, 11)
        self.row4.setSpacing(6)
        self.row4.setObjectName("row4")
        self.btnToggle = QtWidgets.QPushButton(self.keyboard)
        self.btnToggle.setMinimumSize(QtCore.QSize(0, 46))
        self.btnToggle.setMaximumSize(QtCore.QSize(16777215, 46))
        self.btnToggle.setObjectName("btnToggle")
        self.row4.addWidget(self.btnToggle)
        self.space = QtWidgets.QPushButton(self.keyboard)
        self.space.setMinimumSize(QtCore.QSize(200, 46))
        self.space.setMaximumSize(QtCore.QSize(16777215, 46))
        self.space.setObjectName("space")
        self.row4.addWidget(self.space)
        self.btnAt = QtWidgets.QPushButton(self.keyboard)
        self.btnAt.setMinimumSize(QtCore.QSize(0, 46))
        self.btnAt.setMaximumSize(QtCore.QSize(16777215, 46))
        self.btnAt.setObjectName("btnAt")
        self.row4.addWidget(self.btnAt)
        self.btnDot = QtWidgets.QPushButton(self.keyboard)
        self.btnDot.setMinimumSize(QtCore.QSize(0, 46))
        self.btnDot.setMaximumSize(QtCore.QSize(16777215, 46))
        self.btnDot.setObjectName("btnDot")
        self.row4.addWidget(self.btnDot)
        self.btnReturn = QtWidgets.QPushButton(self.keyboard)
        self.btnReturn.setMinimumSize(QtCore.QSize(0, 46))
        self.btnReturn.setMaximumSize(QtCore.QSize(16777215, 46))
        self.btnReturn.setObjectName("btnReturn")
        self.row4.addWidget(self.btnReturn)
        self.verticalLayout.addLayout(self.row4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.keyboard, 1, 1, 1, 1)
        self.lbl_email = QtWidgets.QLabel(self.groupBox)
        self.lbl_email.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_email.setFont(font)
        self.lbl_email.setObjectName("lbl_email")
        self.gridLayout_2.addWidget(self.lbl_email, 0, 0, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(513, 19))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout_2.addWidget(self.lineEdit_email, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 3)

        self.retranslateUi(newLogin)
        QtCore.QMetaObject.connectSlotsByName(newLogin)

    def retranslateUi(self, newLogin):
        _translate = QtCore.QCoreApplication.translate
        newLogin.setWindowTitle(_translate("newLogin", "newLogin"))
        self.btn_login.setText(_translate("newLogin", "Login"))
        self.btn_back.setText(_translate("newLogin", "Back"))
        self.lbl_title.setText(_translate("newLogin", "New Login"))
        self.Q.setText(_translate("newLogin", "Q"))
        self.W.setText(_translate("newLogin", "W"))
        self.E.setText(_translate("newLogin", "E"))
        self.R.setText(_translate("newLogin", "R"))
        self.T.setText(_translate("newLogin", "T"))
        self.Y.setText(_translate("newLogin", "Y"))
        self.U.setText(_translate("newLogin", "U"))
        self.I.setText(_translate("newLogin", "I"))
        self.O.setText(_translate("newLogin", "O"))
        self.P.setText(_translate("newLogin", "P"))
        self.A.setText(_translate("newLogin", "A"))
        self.S.setText(_translate("newLogin", "S"))
        self.D.setText(_translate("newLogin", "D"))
        self.F.setText(_translate("newLogin", "F"))
        self.G.setText(_translate("newLogin", "G"))
        self.H.setText(_translate("newLogin", "H"))
        self.J.setText(_translate("newLogin", "J"))
        self.K.setText(_translate("newLogin", "K"))
        self.L.setText(_translate("newLogin", "L"))
        self.btnShift.setText(_translate("newLogin", "Shift"))
        self.Z.setText(_translate("newLogin", "Z"))
        self.X.setText(_translate("newLogin", "X"))
        self.C.setText(_translate("newLogin", "C"))
        self.V.setText(_translate("newLogin", "V"))
        self.B.setText(_translate("newLogin", "B"))
        self.N.setText(_translate("newLogin", "N"))
        self.M.setText(_translate("newLogin", "M"))
        self.btnDel.setText(_translate("newLogin", "Del"))
        self.btnToggle.setText(_translate("newLogin", "123"))
        self.space.setText(_translate("newLogin", "space"))
        self.btnAt.setText(_translate("newLogin", "@"))
        self.btnDot.setText(_translate("newLogin", "."))
        self.btnReturn.setText(_translate("newLogin", "return"))
        self.lbl_email.setText(_translate("newLogin", "Email:"))

