# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(805, 480)
        self.centralWidget = QtWidgets.QWidget(login)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblTitle = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setScaledContents(True)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout_2.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.lblUsername = QtWidgets.QLabel(self.centralWidget)
        self.lblUsername.setEnabled(True)
        self.lblUsername.setMinimumSize(QtCore.QSize(78, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblUsername.setFont(font)
        self.lblUsername.setIndent(0)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(self.centralWidget)
        self.txtUsername.setMinimumSize(QtCore.QSize(504, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtUsername.setFont(font)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUsername)
        self.lblPassword = QtWidgets.QLabel(self.centralWidget)
        self.lblPassword.setMinimumSize(QtCore.QSize(78, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblPassword.setFont(font)
        self.lblPassword.setScaledContents(True)
        self.lblPassword.setIndent(0)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(self.centralWidget)
        self.txtPassword.setMinimumSize(QtCore.QSize(504, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtPassword.setFont(font)
        self.txtPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.txtPassword.setInputMask("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPassword)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 2, 2)
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout_2.addWidget(self.lblStatus, 0, 1, 1, 1)
        self.btnRegister = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName("btnRegister")
        self.gridLayout_2.addWidget(self.btnRegister, 1, 2, 1, 1)
        self.btnLogin = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.gridLayout_2.addWidget(self.btnLogin, 2, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnExpressUser_2 = QtWidgets.QPushButton(self.centralWidget)
        self.btnExpressUser_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_2.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExpressUser_2.setFont(font)
        self.btnExpressUser_2.setObjectName("btnExpressUser_2")
        self.gridLayout.addWidget(self.btnExpressUser_2, 0, 1, 1, 1)
        self.btnExpressUser_4 = QtWidgets.QPushButton(self.centralWidget)
        self.btnExpressUser_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_4.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExpressUser_4.setFont(font)
        self.btnExpressUser_4.setObjectName("btnExpressUser_4")
        self.gridLayout.addWidget(self.btnExpressUser_4, 1, 0, 1, 1)
        self.btnExpressUser_6 = QtWidgets.QPushButton(self.centralWidget)
        self.btnExpressUser_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_6.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExpressUser_6.setFont(font)
        self.btnExpressUser_6.setObjectName("btnExpressUser_6")
        self.gridLayout.addWidget(self.btnExpressUser_6, 1, 2, 1, 1)
        self.btnExpressUser_1 = QtWidgets.QPushButton(self.centralWidget)
        self.btnExpressUser_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_1.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExpressUser_1.setFont(font)
        self.btnExpressUser_1.setObjectName("btnExpressUser_1")
        self.gridLayout.addWidget(self.btnExpressUser_1, 0, 0, 1, 1)
        self.btnExpressUser_5 = QtWidgets.QPushButton(self.centralWidget)
        self.btnExpressUser_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_5.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExpressUser_5.setFont(font)
        self.btnExpressUser_5.setObjectName("btnExpressUser_5")
        self.gridLayout.addWidget(self.btnExpressUser_5, 1, 1, 1, 1)
        self.btnExpressUser_3 = QtWidgets.QPushButton(self.centralWidget)
        self.btnExpressUser_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_3.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExpressUser_3.setFont(font)
        self.btnExpressUser_3.setObjectName("btnExpressUser_3")
        self.gridLayout.addWidget(self.btnExpressUser_3, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 4, 0, 1, 3)
        self.chkExpressLogin = QtWidgets.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.chkExpressLogin.setFont(font)
        self.chkExpressLogin.setObjectName("chkExpressLogin")
        self.gridLayout_2.addWidget(self.chkExpressLogin, 3, 0, 1, 2)
        login.setCentralWidget(self.centralWidget)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)
        login.setTabOrder(self.txtUsername, self.txtPassword)
        login.setTabOrder(self.txtPassword, self.btnLogin)
        login.setTabOrder(self.btnLogin, self.chkExpressLogin)
        login.setTabOrder(self.chkExpressLogin, self.btnExpressUser_1)
        login.setTabOrder(self.btnExpressUser_1, self.btnExpressUser_2)
        login.setTabOrder(self.btnExpressUser_2, self.btnExpressUser_3)
        login.setTabOrder(self.btnExpressUser_3, self.btnExpressUser_4)
        login.setTabOrder(self.btnExpressUser_4, self.btnExpressUser_5)
        login.setTabOrder(self.btnExpressUser_5, self.btnExpressUser_6)
        login.setTabOrder(self.btnExpressUser_6, self.btnRegister)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "smartScaleGUI"))
        self.lblTitle.setText(_translate("login", "Please enter Username and Password : "))
        self.lblUsername.setText(_translate("login", "Username :"))
        self.lblPassword.setText(_translate("login", "Password :"))
        self.btnRegister.setText(_translate("login", "New User Register"))
        self.btnLogin.setText(_translate("login", "Login"))
        self.btnExpressUser_2.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_4.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_6.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_1.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_5.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_3.setText(_translate("login", "Express Login not assigned"))
        self.chkExpressLogin.setText(_translate("login", "Remember me for Express Login"))

