# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userRegister.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userRegister(object):
    def setupUi(self, userRegister):
        userRegister.setObjectName("userRegister")
        userRegister.resize(1024, 600)
        self.centralWidget = QtWidgets.QWidget(userRegister)
        self.centralWidget.setObjectName("centralWidget")
        self.btnCancel = QtWidgets.QPushButton(self.centralWidget)
        self.btnCancel.setGeometry(QtCore.QRect(800, 110, 201, 31))
        self.btnCancel.setObjectName("btnCancel")
        self.btnRegister = QtWidgets.QPushButton(self.centralWidget)
        self.btnRegister.setGeometry(QtCore.QRect(800, 60, 201, 31))
        self.btnRegister.setObjectName("btnRegister")
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        self.lblStatus.setGeometry(QtCore.QRect(20, 10, 991, 41))
        self.lblStatus.setObjectName("lblStatus")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 50, 771, 491))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.lblConfirmPassword = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblConfirmPassword.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.datDoB = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.datDoB.setGeometry(QtCore.QRect(130, 250, 621, 31))
        self.datDoB.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.datDoB.setObjectName("datDoB")
        self.lblFirstname = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblFirstname.setGeometry(QtCore.QRect(20, 170, 81, 21))
        self.lblFirstname.setObjectName("lblFirstname")
        self.lblLastname = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblLastname.setGeometry(QtCore.QRect(20, 210, 81, 21))
        self.lblLastname.setObjectName("lblLastname")
        self.rbnMale = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbnMale.setGeometry(QtCore.QRect(160, 290, 82, 17))
        self.rbnMale.setObjectName("rbnMale")
        self.lblEmail = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblEmail.setGeometry(QtCore.QRect(20, 130, 81, 21))
        self.lblEmail.setObjectName("lblEmail")
        self.lblDoB = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblDoB.setGeometry(QtCore.QRect(20, 250, 81, 21))
        self.lblDoB.setObjectName("lblDoB")
        self.lblPassword = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblPassword.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.lblPassword.setObjectName("lblPassword")
        self.lblGender = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblGender.setGeometry(QtCore.QRect(20, 290, 81, 21))
        self.lblGender.setObjectName("lblGender")
        self.lblUsername = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblUsername.setGeometry(QtCore.QRect(20, 12, 71, 21))
        self.lblUsername.setObjectName("lblUsername")
        self.lblWeight = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblWeight.setGeometry(QtCore.QRect(20, 360, 81, 21))
        self.lblWeight.setObjectName("lblWeight")
        self.rbnFemale = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbnFemale.setGeometry(QtCore.QRect(270, 290, 82, 17))
        self.rbnFemale.setObjectName("rbnFemale")
        self.lblHeight = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblHeight.setGeometry(QtCore.QRect(20, 320, 81, 21))
        self.lblHeight.setObjectName("lblHeight")
        self.txtUsername = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtUsername.setGeometry(QtCore.QRect(130, 10, 621, 31))
        self.txtUsername.setObjectName("txtUsername")
        self.txtPassword = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtPassword.setGeometry(QtCore.QRect(130, 50, 621, 31))
        self.txtPassword.setObjectName("txtPassword")
        self.txtConfirmPassword = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtConfirmPassword.setGeometry(QtCore.QRect(130, 90, 621, 31))
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.txtEmail = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtEmail.setGeometry(QtCore.QRect(130, 130, 621, 31))
        self.txtEmail.setObjectName("txtEmail")
        self.txtFirstname = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtFirstname.setGeometry(QtCore.QRect(130, 170, 621, 31))
        self.txtFirstname.setObjectName("txtFirstname")
        self.txtLastname = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtLastname.setGeometry(QtCore.QRect(130, 210, 621, 31))
        self.txtLastname.setObjectName("txtLastname")
        self.textHeight = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.textHeight.setGeometry(QtCore.QRect(130, 320, 621, 31))
        self.textHeight.setObjectName("textHeight")
        self.txtWeight = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtWeight.setGeometry(QtCore.QRect(130, 360, 621, 31))
        self.txtWeight.setObjectName("txtWeight")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        userRegister.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(userRegister)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menuBar.setObjectName("menuBar")
        userRegister.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(userRegister)
        self.mainToolBar.setObjectName("mainToolBar")
        userRegister.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(userRegister)
        self.statusBar.setObjectName("statusBar")
        userRegister.setStatusBar(self.statusBar)

        self.retranslateUi(userRegister)
        QtCore.QMetaObject.connectSlotsByName(userRegister)

    def retranslateUi(self, userRegister):
        _translate = QtCore.QCoreApplication.translate
        userRegister.setWindowTitle(_translate("userRegister", "smartScaleGUI"))
        self.btnCancel.setText(_translate("userRegister", "Cancel"))
        self.btnRegister.setText(_translate("userRegister", "Register"))
        self.lblStatus.setText(_translate("userRegister", "<html><head/><body><p>Please enter the following details :</p></body></html>"))
        self.lblConfirmPassword.setText(_translate("userRegister", "Confirm Password :"))
        self.lblFirstname.setText(_translate("userRegister", "Firstname :"))
        self.lblLastname.setText(_translate("userRegister", "Lastname :"))
        self.rbnMale.setText(_translate("userRegister", "Male"))
        self.lblEmail.setText(_translate("userRegister", "Email :"))
        self.lblDoB.setText(_translate("userRegister", "Date of Birth :"))
        self.lblPassword.setText(_translate("userRegister", "Password :"))
        self.lblGender.setText(_translate("userRegister", "Gender :"))
        self.lblUsername.setText(_translate("userRegister", "Username :"))
        self.lblWeight.setText(_translate("userRegister", "Weight (kg) :"))
        self.rbnFemale.setText(_translate("userRegister", "Female"))
        self.lblHeight.setText(_translate("userRegister", "Height (cm) :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userRegister = QtWidgets.QMainWindow()
    ui = Ui_userRegister()
    ui.setupUi(userRegister)
    userRegister.show()
    sys.exit(app.exec_())

