# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userDetails.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userDetails(object):
    def setupUi(self, userDetails):
        userDetails.setObjectName("userDetails")
        userDetails.resize(1024, 565)
        self.centralWidget = QtWidgets.QWidget(userDetails)
        self.centralWidget.setObjectName("centralWidget")
        self.btnBack = QtWidgets.QPushButton(self.centralWidget)
        self.btnBack.setGeometry(QtCore.QRect(64, 450, 201, 31))
        self.btnBack.setObjectName("btnBack")
        self.lblUserDetails = QtWidgets.QLabel(self.centralWidget)
        self.lblUserDetails.setGeometry(QtCore.QRect(74, 20, 201, 31))
        self.lblUserDetails.setObjectName("lblUserDetails")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(580, 50, 361, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grdGraphs = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grdGraphs.setContentsMargins(11, 11, 11, 11)
        self.grdGraphs.setSpacing(6)
        self.grdGraphs.setObjectName("grdGraphs")
        self.grphVisuals2 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.grphVisuals2.setObjectName("grphVisuals2")
        self.grdGraphs.addWidget(self.grphVisuals2, 3, 0, 1, 1)
        self.grphCurretvsLast = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.grphCurretvsLast.setObjectName("grphCurretvsLast")
        self.grdGraphs.addWidget(self.grphCurretvsLast, 1, 0, 1, 1)
        self.lblCurrenvsLast = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCurrenvsLast.setObjectName("lblCurrenvsLast")
        self.grdGraphs.addWidget(self.lblCurrenvsLast, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lblVisuals2Title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblVisuals2Title.setObjectName("lblVisuals2Title")
        self.grdGraphs.addWidget(self.lblVisuals2Title, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.frmFitnessMeasure2 = QtWidgets.QFrame(self.centralWidget)
        self.frmFitnessMeasure2.setGeometry(QtCore.QRect(304, 280, 191, 121))
        self.frmFitnessMeasure2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFitnessMeasure2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFitnessMeasure2.setObjectName("frmFitnessMeasure2")
        self.prgsFitnessMeausre2 = QtWidgets.QProgressBar(self.frmFitnessMeasure2)
        self.prgsFitnessMeausre2.setGeometry(QtCore.QRect(27, 30, 131, 23))
        self.prgsFitnessMeausre2.setProperty("value", 24)
        self.prgsFitnessMeausre2.setObjectName("prgsFitnessMeausre2")
        self.lblFitnessMeasure2 = QtWidgets.QLabel(self.frmFitnessMeasure2)
        self.lblFitnessMeasure2.setGeometry(QtCore.QRect(30, 70, 121, 31))
        self.lblFitnessMeasure2.setObjectName("lblFitnessMeasure2")
        self.frmDailyCals = QtWidgets.QFrame(self.centralWidget)
        self.frmDailyCals.setGeometry(QtCore.QRect(74, 280, 191, 121))
        self.frmDailyCals.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmDailyCals.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmDailyCals.setObjectName("frmDailyCals")
        self.pgrsDailyIntake = QtWidgets.QProgressBar(self.frmDailyCals)
        self.pgrsDailyIntake.setGeometry(QtCore.QRect(30, 30, 131, 20))
        self.pgrsDailyIntake.setProperty("value", 24)
        self.pgrsDailyIntake.setObjectName("pgrsDailyIntake")
        self.lblDailyCals = QtWidgets.QLabel(self.frmDailyCals)
        self.lblDailyCals.setGeometry(QtCore.QRect(30, 80, 131, 16))
        self.lblDailyCals.setObjectName("lblDailyCals")
        self.lblBMI = QtWidgets.QLabel(self.centralWidget)
        self.lblBMI.setGeometry(QtCore.QRect(95, 187, 27, 16))
        self.lblBMI.setObjectName("lblBMI")
        self.lblName = QtWidgets.QLabel(self.centralWidget)
        self.lblName.setGeometry(QtCore.QRect(82, 91, 40, 16))
        self.lblName.setObjectName("lblName")
        self.lblAge = QtWidgets.QLabel(self.centralWidget)
        self.lblAge.setGeometry(QtCore.QRect(94, 115, 28, 16))
        self.lblAge.setObjectName("lblAge")
        self.lblUserHeight = QtWidgets.QLabel(self.centralWidget)
        self.lblUserHeight.setGeometry(QtCore.QRect(130, 139, 371, 16))
        self.lblUserHeight.setObjectName("lblUserHeight")
        self.lblUserWeight = QtWidgets.QLabel(self.centralWidget)
        self.lblUserWeight.setGeometry(QtCore.QRect(130, 163, 371, 16))
        self.lblUserWeight.setObjectName("lblUserWeight")
        self.lblWeight = QtWidgets.QLabel(self.centralWidget)
        self.lblWeight.setGeometry(QtCore.QRect(75, 163, 47, 16))
        self.lblWeight.setObjectName("lblWeight")
        self.lblBMR = QtWidgets.QLabel(self.centralWidget)
        self.lblBMR.setGeometry(QtCore.QRect(90, 211, 32, 16))
        self.lblBMR.setObjectName("lblBMR")
        self.lbluserBMR = QtWidgets.QLabel(self.centralWidget)
        self.lbluserBMR.setGeometry(QtCore.QRect(130, 211, 371, 16))
        self.lbluserBMR.setObjectName("lbluserBMR")
        self.lblHeight = QtWidgets.QLabel(self.centralWidget)
        self.lblHeight.setGeometry(QtCore.QRect(78, 139, 44, 16))
        self.lblHeight.setObjectName("lblHeight")
        self.lblUserBMI = QtWidgets.QLabel(self.centralWidget)
        self.lblUserBMI.setGeometry(QtCore.QRect(130, 187, 371, 16))
        self.lblUserBMI.setObjectName("lblUserBMI")
        self.lblUserName = QtWidgets.QLabel(self.centralWidget)
        self.lblUserName.setGeometry(QtCore.QRect(130, 91, 371, 16))
        self.lblUserName.setObjectName("lblUserName")
        self.lblUserAge = QtWidgets.QLabel(self.centralWidget)
        self.lblUserAge.setGeometry(QtCore.QRect(130, 115, 371, 16))
        self.lblUserAge.setObjectName("lblUserAge")
        userDetails.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(userDetails)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menuBar.setObjectName("menuBar")
        userDetails.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(userDetails)
        self.mainToolBar.setObjectName("mainToolBar")
        userDetails.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(userDetails)
        self.statusBar.setObjectName("statusBar")
        userDetails.setStatusBar(self.statusBar)

        self.retranslateUi(userDetails)
        QtCore.QMetaObject.connectSlotsByName(userDetails)

    def retranslateUi(self, userDetails):
        _translate = QtCore.QCoreApplication.translate
        userDetails.setWindowTitle(_translate("userDetails", "smartScaleGUI"))
        self.btnBack.setText(_translate("userDetails", "Back"))
        self.lblUserDetails.setText(_translate("userDetails", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">User Details</span></p></body></html>"))
        self.lblCurrenvsLast.setText(_translate("userDetails", "This week\'s vs Last Week\'s Intake"))
        self.lblVisuals2Title.setText(_translate("userDetails", "Some other graphical data representation"))
        self.lblFitnessMeasure2.setText(_translate("userDetails", "Some other measure"))
        self.lblDailyCals.setText(_translate("userDetails", "xxxx/xxxx kcals"))
        self.lblBMI.setText(_translate("userDetails", "BMI:"))
        self.lblName.setText(_translate("userDetails", "Name:"))
        self.lblAge.setText(_translate("userDetails", "Age:"))
        self.lblUserHeight.setText(_translate("userDetails", "usersheight"))
        self.lblUserWeight.setText(_translate("userDetails", "usersweight"))
        self.lblWeight.setText(_translate("userDetails", "Weight:"))
        self.lblBMR.setText(_translate("userDetails", "BMR:"))
        self.lbluserBMR.setText(_translate("userDetails", "usersbmr"))
        self.lblHeight.setText(_translate("userDetails", "Height:"))
        self.lblUserBMI.setText(_translate("userDetails", "usersbmi"))
        self.lblUserName.setText(_translate("userDetails", "usersname"))
        self.lblUserAge.setText(_translate("userDetails", "usersage"))

