# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genderSelection.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_genderSelection(object):
    def setupUi(self, genderSelection):
        genderSelection.setObjectName("genderSelection")
        genderSelection.resize(800, 484)
        self.gridLayout = QtWidgets.QGridLayout(genderSelection)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(genderSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.selectionBox = QtWidgets.QFrame(self.groupBox)
        self.selectionBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectionBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectionBox.setObjectName("selectionBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.selectionBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.row1 = QtWidgets.QHBoxLayout()
        self.row1.setContentsMargins(11, 11, 11, 11)
        self.row1.setSpacing(6)
        self.row1.setObjectName("row1")
        self.btn_male = QtWidgets.QPushButton(self.selectionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_male.sizePolicy().hasHeightForWidth())
        self.btn_male.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_male.setFont(font)
        self.btn_male.setObjectName("btn_male")
        self.row1.addWidget(self.btn_male)
        self.btn_female = QtWidgets.QPushButton(self.selectionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_female.sizePolicy().hasHeightForWidth())
        self.btn_female.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_female.setFont(font)
        self.btn_female.setObjectName("btn_female")
        self.row1.addWidget(self.btn_female)
        self.verticalLayout.addLayout(self.row1)
        self.gridLayout_2.addWidget(self.selectionBox, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 3)
        self.btn_back = QtWidgets.QPushButton(genderSelection)
        self.btn_back.setMinimumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(487, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.lbl_title = QtWidgets.QLabel(genderSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout.addWidget(self.lbl_title, 0, 0, 1, 3)

        self.retranslateUi(genderSelection)
        QtCore.QMetaObject.connectSlotsByName(genderSelection)

    def retranslateUi(self, genderSelection):
        _translate = QtCore.QCoreApplication.translate
        genderSelection.setWindowTitle(_translate("genderSelection", "newLogin"))
        self.label.setText(_translate("genderSelection", "Please select one of the following:"))
        self.btn_male.setText(_translate("genderSelection", "Male"))
        self.btn_female.setText(_translate("genderSelection", "Female"))
        self.btn_back.setText(_translate("genderSelection", "Back"))
        self.lbl_title.setText(_translate("genderSelection", "-"))

