# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1024, 565)
        self.centralWidget = QtWidgets.QWidget(login)
        self.centralWidget.setObjectName("centralWidget")
        self.btnLogin = QtWidgets.QPushButton(self.centralWidget)
        self.btnLogin.setGeometry(QtCore.QRect(780, 60, 221, 31))
        self.btnLogin.setObjectName("btnLogin")
        self.btnRegister = QtWidgets.QPushButton(self.centralWidget)
        self.btnRegister.setGeometry(QtCore.QRect(780, 10, 221, 31))
        self.btnRegister.setObjectName("btnRegister")
        self.lblUsername = QtWidgets.QLabel(self.centralWidget)
        self.lblUsername.setGeometry(QtCore.QRect(20, 62, 71, 21))
        self.lblUsername.setObjectName("lblUsername")
        self.lblPassword = QtWidgets.QLabel(self.centralWidget)
        self.lblPassword.setGeometry(QtCore.QRect(20, 112, 81, 21))
        self.lblPassword.setObjectName("lblPassword")
        self.lblTitle = QtWidgets.QLabel(self.centralWidget)
        self.lblTitle.setGeometry(QtCore.QRect(20, 10, 281, 41))
        self.lblTitle.setObjectName("lblTitle")
        self.txtUsername = QtWidgets.QLineEdit(self.centralWidget)
        self.txtUsername.setGeometry(QtCore.QRect(110, 60, 641, 31))
        self.txtUsername.setObjectName("txtUsername")
        self.txtPassword = QtWidgets.QLineEdit(self.centralWidget)
        self.txtPassword.setGeometry(QtCore.QRect(110, 110, 641, 31))
        self.txtPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.txtPassword.setInputMask("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        self.lblStatus.setGeometry(QtCore.QRect(290, 10, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 180, 981, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnExpressUser_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExpressUser_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_2.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_2.setSizePolicy(sizePolicy)
        self.btnExpressUser_2.setObjectName("btnExpressUser_2")
        self.gridLayout.addWidget(self.btnExpressUser_2, 0, 1, 1, 1)
        self.btnExpressUser_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExpressUser_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_5.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_5.setSizePolicy(sizePolicy)
        self.btnExpressUser_5.setObjectName("btnExpressUser_5")
        self.gridLayout.addWidget(self.btnExpressUser_5, 1, 1, 1, 1)
        self.btnExpressUser_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExpressUser_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_1.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_1.setSizePolicy(sizePolicy)
        self.btnExpressUser_1.setObjectName("btnExpressUser_1")
        self.gridLayout.addWidget(self.btnExpressUser_1, 0, 0, 1, 1)
        self.btnExpressUser_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExpressUser_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_4.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_4.setSizePolicy(sizePolicy)
        self.btnExpressUser_4.setObjectName("btnExpressUser_4")
        self.gridLayout.addWidget(self.btnExpressUser_4, 1, 0, 1, 1)
        self.btnExpressUser_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExpressUser_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_3.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_3.setSizePolicy(sizePolicy)
        self.btnExpressUser_3.setObjectName("btnExpressUser_3")
        self.gridLayout.addWidget(self.btnExpressUser_3, 0, 2, 1, 1)
        self.btnExpressUser_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExpressUser_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExpressUser_6.sizePolicy().hasHeightForWidth())
        self.btnExpressUser_6.setSizePolicy(sizePolicy)
        self.btnExpressUser_6.setObjectName("btnExpressUser_6")
        self.gridLayout.addWidget(self.btnExpressUser_6, 1, 2, 1, 1)
        self.chkExpressLogin = QtWidgets.QCheckBox(self.centralWidget)
        self.chkExpressLogin.setGeometry(QtCore.QRect(780, 110, 221, 41))
        self.chkExpressLogin.setObjectName("chkExpressLogin")
        self.lblTitle_2 = QtWidgets.QLabel(self.centralWidget)
        self.lblTitle_2.setGeometry(QtCore.QRect(20, 150, 281, 31))
        self.lblTitle_2.setObjectName("lblTitle_2")
        login.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(login)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menuBar.setObjectName("menuBar")
        login.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(login)
        self.mainToolBar.setObjectName("mainToolBar")
        login.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(login)
        self.statusBar.setObjectName("statusBar")
        login.setStatusBar(self.statusBar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "smartScaleGUI"))
        self.btnLogin.setText(_translate("login", "Login"))
        self.btnRegister.setText(_translate("login", "New User Register"))
        self.lblUsername.setText(_translate("login", "Username :"))
        self.lblPassword.setText(_translate("login", "Password :"))
        self.lblTitle.setText(_translate("login", "Please enter Username and Password : "))
        self.btnExpressUser_2.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_5.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_1.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_4.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_3.setText(_translate("login", "Express Login not assigned"))
        self.btnExpressUser_6.setText(_translate("login", "Express Login not assigned"))
        self.chkExpressLogin.setText(_translate("login", "Remember me for Express Login"))
        self.lblTitle_2.setText(_translate("login", "Express Login:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())

