# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userDetailChange.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userDetailChange(object):
    def setupUi(self, userDetailChange):
        userDetailChange.setObjectName("userDetailChange")
        userDetailChange.resize(1024, 565)
        self.centralWidget = QtWidgets.QWidget(userDetailChange)
        self.centralWidget.setObjectName("centralWidget")
        self.btnCancel = QtWidgets.QPushButton(self.centralWidget)
        self.btnCancel.setGeometry(QtCore.QRect(800, 110, 201, 31))
        self.btnCancel.setObjectName("btnCancel")
        self.btnSubmitChanges = QtWidgets.QPushButton(self.centralWidget)
        self.btnSubmitChanges.setGeometry(QtCore.QRect(800, 60, 201, 31))
        self.btnSubmitChanges.setObjectName("btnSubmitChanges")
        self.lblTitle = QtWidgets.QLabel(self.centralWidget)
        self.lblTitle.setGeometry(QtCore.QRect(20, 10, 231, 41))
        self.lblTitle.setObjectName("lblTitle")
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        self.lblStatus.setGeometry(QtCore.QRect(250, 10, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 741, 401))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblEmail = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtEmail)
        self.lblFirstname = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblFirstname.setObjectName("lblFirstname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblFirstname)
        self.txtFirstname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtFirstname.setObjectName("txtFirstname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtFirstname)
        self.lblLastname = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblLastname.setObjectName("lblLastname")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblLastname)
        self.txtLastname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtLastname.setObjectName("txtLastname")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtLastname)
        self.lblDoB = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblDoB.setObjectName("lblDoB")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblDoB)
        self.datDoB = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.datDoB.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.datDoB.setCalendarPopup(True)
        self.datDoB.setObjectName("datDoB")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.datDoB)
        self.lblGender = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblGender.setObjectName("lblGender")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblGender)
        self.rbnMale = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rbnMale.setObjectName("rbnMale")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rbnMale)
        self.rbnFemale = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rbnFemale.setObjectName("rbnFemale")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rbnFemale)
        self.lblHeight = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblHeight.setObjectName("lblHeight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblHeight)
        self.txtHeight = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtHeight.setObjectName("txtHeight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtHeight)
        self.lblWeight = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblWeight.setObjectName("lblWeight")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lblWeight)
        self.txtWeight = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtWeight.setObjectName("txtWeight")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txtWeight)
        self.chkExpressLogin = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chkExpressLogin.setObjectName("chkExpressLogin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.chkExpressLogin)
        self.lblExpressLogin = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblExpressLogin.setObjectName("lblExpressLogin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lblExpressLogin)
        self.txtPassword = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtPassword)
        self.lblPassword = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        userDetailChange.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(userDetailChange)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menuBar.setObjectName("menuBar")
        userDetailChange.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(userDetailChange)
        self.mainToolBar.setObjectName("mainToolBar")
        userDetailChange.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(userDetailChange)
        self.statusBar.setObjectName("statusBar")
        userDetailChange.setStatusBar(self.statusBar)

        self.retranslateUi(userDetailChange)
        QtCore.QMetaObject.connectSlotsByName(userDetailChange)

    def retranslateUi(self, userDetailChange):
        _translate = QtCore.QCoreApplication.translate
        userDetailChange.setWindowTitle(_translate("userDetailChange", "smartScaleGUI"))
        self.btnCancel.setText(_translate("userDetailChange", "Cancel"))
        self.btnSubmitChanges.setText(_translate("userDetailChange", "Submit Changes"))
        self.lblTitle.setText(_translate("userDetailChange", "<html><head/><body><p>Please enter the following details :</p></body></html>"))
        self.lblEmail.setText(_translate("userDetailChange", "Email :"))
        self.lblFirstname.setText(_translate("userDetailChange", "Firstname :"))
        self.lblLastname.setText(_translate("userDetailChange", "Lastname :"))
        self.lblDoB.setText(_translate("userDetailChange", "Date of Birth :"))
        self.datDoB.setDisplayFormat(_translate("userDetailChange", "dd-MMM-yyyy"))
        self.lblGender.setText(_translate("userDetailChange", "Gender :"))
        self.rbnMale.setText(_translate("userDetailChange", "Male"))
        self.rbnFemale.setText(_translate("userDetailChange", "Female"))
        self.lblHeight.setText(_translate("userDetailChange", "Height (cm) :"))
        self.lblWeight.setText(_translate("userDetailChange", "Weight (kg) :"))
        self.chkExpressLogin.setText(_translate("userDetailChange", "Activated"))
        self.lblExpressLogin.setText(_translate("userDetailChange", "Expressed Login: :"))
        self.lblPassword.setText(_translate("userDetailChange", "Current Password :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userDetailChange = QtWidgets.QMainWindow()
    ui = Ui_userDetailChange()
    ui.setupUi(userDetailChange)
    userDetailChange.show()
    sys.exit(app.exec_())

