# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userDetailChange.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userDetailChange(object):
    def setupUi(self, userDetailChange):
        userDetailChange.setObjectName("userDetailChange")
        userDetailChange.resize(1024, 600)
        self.centralWidget = QtWidgets.QWidget(userDetailChange)
        self.centralWidget.setObjectName("centralWidget")
        self.btnCancel = QtWidgets.QPushButton(self.centralWidget)
        self.btnCancel.setGeometry(QtCore.QRect(800, 110, 201, 31))
        self.btnCancel.setObjectName("btnCancel")
        self.btnSubmitChanges = QtWidgets.QPushButton(self.centralWidget)
        self.btnSubmitChanges.setGeometry(QtCore.QRect(800, 60, 201, 31))
        self.btnSubmitChanges.setObjectName("btnSubmitChanges")
        self.lblTitle = QtWidgets.QLabel(self.centralWidget)
        self.lblTitle.setGeometry(QtCore.QRect(20, 10, 171, 41))
        self.lblTitle.setObjectName("lblTitle")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 120, 771, 421))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.datDoB = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.datDoB.setGeometry(QtCore.QRect(130, 140, 621, 31))
        self.datDoB.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.datDoB.setCalendarPopup(True)
        self.datDoB.setObjectName("datDoB")
        self.lblFirstname = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblFirstname.setGeometry(QtCore.QRect(20, 60, 81, 21))
        self.lblFirstname.setObjectName("lblFirstname")
        self.lblLastname = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblLastname.setGeometry(QtCore.QRect(20, 100, 81, 21))
        self.lblLastname.setObjectName("lblLastname")
        self.rbnMale = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbnMale.setGeometry(QtCore.QRect(160, 180, 82, 17))
        self.rbnMale.setObjectName("rbnMale")
        self.lblEmail = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblEmail.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.lblEmail.setObjectName("lblEmail")
        self.lblDoB = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblDoB.setGeometry(QtCore.QRect(20, 140, 81, 21))
        self.lblDoB.setObjectName("lblDoB")
        self.lblGender = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblGender.setGeometry(QtCore.QRect(20, 180, 81, 21))
        self.lblGender.setObjectName("lblGender")
        self.lblWeight = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblWeight.setGeometry(QtCore.QRect(20, 250, 81, 21))
        self.lblWeight.setObjectName("lblWeight")
        self.rbnFemale = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbnFemale.setGeometry(QtCore.QRect(270, 180, 82, 17))
        self.rbnFemale.setObjectName("rbnFemale")
        self.lblHeight = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblHeight.setGeometry(QtCore.QRect(20, 210, 81, 21))
        self.lblHeight.setObjectName("lblHeight")
        self.txtEmail = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtEmail.setGeometry(QtCore.QRect(130, 20, 621, 31))
        self.txtEmail.setObjectName("txtEmail")
        self.txtFirstname = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtFirstname.setGeometry(QtCore.QRect(130, 60, 621, 31))
        self.txtFirstname.setObjectName("txtFirstname")
        self.txtLastname = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtLastname.setGeometry(QtCore.QRect(130, 100, 621, 31))
        self.txtLastname.setObjectName("txtLastname")
        self.txtHeight = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtHeight.setGeometry(QtCore.QRect(130, 210, 621, 31))
        self.txtHeight.setObjectName("txtHeight")
        self.txtWeight = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtWeight.setGeometry(QtCore.QRect(130, 250, 621, 31))
        self.txtWeight.setObjectName("txtWeight")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        self.lblStatus.setGeometry(QtCore.QRect(250, 10, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.txtPassword = QtWidgets.QLineEdit(self.centralWidget)
        self.txtPassword.setGeometry(QtCore.QRect(140, 60, 621, 31))
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.lblPassword = QtWidgets.QLabel(self.centralWidget)
        self.lblPassword.setGeometry(QtCore.QRect(20, 60, 91, 21))
        self.lblPassword.setObjectName("lblPassword")
        userDetailChange.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(userDetailChange)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menuBar.setObjectName("menuBar")
        userDetailChange.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(userDetailChange)
        self.mainToolBar.setObjectName("mainToolBar")
        userDetailChange.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(userDetailChange)
        self.statusBar.setObjectName("statusBar")
        userDetailChange.setStatusBar(self.statusBar)

        self.retranslateUi(userDetailChange)
        QtCore.QMetaObject.connectSlotsByName(userDetailChange)

    def retranslateUi(self, userDetailChange):
        _translate = QtCore.QCoreApplication.translate
        userDetailChange.setWindowTitle(_translate("userDetailChange", "smartScaleGUI"))
        self.btnCancel.setText(_translate("userDetailChange", "Cancel"))
        self.btnSubmitChanges.setText(_translate("userDetailChange", "Submit Changes"))
        self.lblTitle.setText(_translate("userDetailChange", "<html><head/><body><p>Please enter the following details :</p></body></html>"))
        self.datDoB.setDisplayFormat(_translate("userDetailChange", "dd-MMM-yyyy"))
        self.lblFirstname.setText(_translate("userDetailChange", "Firstname :"))
        self.lblLastname.setText(_translate("userDetailChange", "Lastname :"))
        self.rbnMale.setText(_translate("userDetailChange", "Male"))
        self.lblEmail.setText(_translate("userDetailChange", "Email :"))
        self.lblDoB.setText(_translate("userDetailChange", "Date of Birth :"))
        self.lblGender.setText(_translate("userDetailChange", "Gender :"))
        self.lblWeight.setText(_translate("userDetailChange", "Weight (kg) :"))
        self.rbnFemale.setText(_translate("userDetailChange", "Female"))
        self.lblHeight.setText(_translate("userDetailChange", "Height (cm) :"))
        self.lblPassword.setText(_translate("userDetailChange", "Current Password :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userDetailChange = QtWidgets.QMainWindow()
    ui = Ui_userDetailChange()
    ui.setupUi(userDetailChange)
    userDetailChange.show()
    sys.exit(app.exec_())

