# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getWeight.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication

class Ui_getWeight(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self,getWeight):
        # set default font
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        # 
        getWeight.setObjectName("getWeight")
        getWeight.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(getWeight)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setMinimumSize(QtCore.QSize(320, 90))
        self.frame.setMaximumSize(QtCore.QSize(320, 90))
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # gridLayout_4 contains the weight display
        self.lcdWeight = QtWidgets.QLCDNumber(self.frame)
        self.lcdWeight.setFont(font)
        self.lcdWeight.setObjectName("lcdWeight")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_4.addWidget(self.lcdWeight, 0, 0, 1, 1)
        # set 'g', which is to be displayed next to the weight
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(75)
        self.lblGrams = QtWidgets.QLabel(self.frame)
        self.lblGrams.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lblGrams.setFont(font)
        self.lblGrams.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGrams.setObjectName("lblGrams")
        self.gridLayout_4.addWidget(self.lblGrams, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 7, 1, 3, 5)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        # the nutritional information is contained within 'groupbox'
        font.setPointSize(14)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.groupBox, 1, 6, 5, 2)
        font.setPointSize(11)
        self.lblEnergy = QtWidgets.QLabel(self.groupBox)
        self.lblEnergy.setMaximumSize(QtCore.QSize(132, 16777215))
        self.lblEnergy.setFont(font)
        self.lblEnergy.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblEnergy.setAutoFillBackground(False)
        self.lblEnergy.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblEnergy.setLineWidth(0)
        self.lblEnergy.setScaledContents(True)
        self.lblEnergy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEnergy.setWordWrap(False)
        self.lblEnergy.setIndent(-1)
        self.lblEnergy.setObjectName("lblEnergy")
        self.gridLayout_3.addWidget(self.lblEnergy, 0, 0, 1, 1)
        self.lblEnergyVal = QtWidgets.QLabel(self.groupBox)
        self.lblEnergyVal.setFont(font)
        self.lblEnergyVal.setAutoFillBackground(False)
        self.lblEnergyVal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblEnergyVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEnergyVal.setObjectName("lblEnergyVal")
        self.gridLayout_3.addWidget(self.lblEnergyVal, 0, 1, 1, 1)
        self.lblProtein = QtWidgets.QLabel(self.groupBox)
        self.lblProtein.setMaximumSize(QtCore.QSize(132, 16777215))
        self.lblProtein.setFont(font)
        self.lblProtein.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblProtein.setAutoFillBackground(False)
        self.lblProtein.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblProtein.setLineWidth(0)
        self.lblProtein.setScaledContents(True)
        self.lblProtein.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblProtein.setWordWrap(False)
        self.lblProtein.setIndent(-1)
        self.lblProtein.setObjectName("lblProtein")
        self.gridLayout_3.addWidget(self.lblProtein, 1, 0, 1, 1)
        self.lblProteinVal = QtWidgets.QLabel(self.groupBox)
        self.lblProteinVal.setFont(font)
        self.lblProteinVal.setAutoFillBackground(False)
        self.lblProteinVal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblProteinVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblProteinVal.setObjectName("lblProteinVal")
        self.gridLayout_3.addWidget(self.lblProteinVal, 1, 1, 1, 1)
        self.lblSugar = QtWidgets.QLabel(self.groupBox)
        self.lblSugar.setMaximumSize(QtCore.QSize(132, 16777215))
        self.lblSugar.setFont(font)
        self.lblSugar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblSugar.setAutoFillBackground(False)
        self.lblSugar.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblSugar.setLineWidth(0)
        self.lblSugar.setScaledContents(True)
        self.lblSugar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSugar.setWordWrap(False)
        self.lblSugar.setIndent(-1)
        self.lblSugar.setObjectName("lblSugar")
        self.gridLayout_3.addWidget(self.lblSugar, 2, 0, 1, 1)
        self.lblSugarVal = QtWidgets.QLabel(self.groupBox)
        self.lblSugarVal.setFont(font)
        self.lblSugarVal.setAutoFillBackground(False)
        self.lblSugarVal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblSugarVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSugarVal.setObjectName("lblSugarVal")
        self.gridLayout_3.addWidget(self.lblSugarVal, 2, 1, 1, 1)
        self.lblFibre = QtWidgets.QLabel(self.groupBox)
        self.lblFibre.setMaximumSize(QtCore.QSize(132, 16777215))
        self.lblFibre.setFont(font)
        self.lblFibre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblFibre.setAutoFillBackground(False)
        self.lblFibre.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblFibre.setLineWidth(0)
        self.lblFibre.setScaledContents(True)
        self.lblFibre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFibre.setWordWrap(False)
        self.lblFibre.setIndent(-1)
        self.lblFibre.setObjectName("lblFibre")
        self.gridLayout_3.addWidget(self.lblFibre, 3, 0, 1, 1)
        self.lblFbreVal = QtWidgets.QLabel(self.groupBox)
        self.lblFbreVal.setFont(font)
        self.lblFbreVal.setAutoFillBackground(False)
        self.lblFbreVal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblFbreVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFbreVal.setObjectName("lblFbreVal")
        self.gridLayout_3.addWidget(self.lblFbreVal, 3, 1, 1, 1)
        self.lblFat = QtWidgets.QLabel(self.groupBox)
        self.lblFat.setMaximumSize(QtCore.QSize(132, 16777215))
        self.lblFat.setFont(font)
        self.lblFat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblFat.setAutoFillBackground(False)
        self.lblFat.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblFat.setLineWidth(0)
        self.lblFat.setScaledContents(True)
        self.lblFat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFat.setWordWrap(False)
        self.lblFat.setIndent(-1)
        self.lblFat.setObjectName("lblFat")
        self.gridLayout_3.addWidget(self.lblFat, 4, 0, 1, 1)
        self.lblFatVal = QtWidgets.QLabel(self.groupBox)
        self.lblFatVal.setFont(font)
        self.lblFatVal.setAutoFillBackground(False)
        self.lblFatVal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblFatVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFatVal.setObjectName("lblFatVal")
        self.gridLayout_3.addWidget(self.lblFatVal, 4, 1, 1, 1)
        self.lblSalt = QtWidgets.QLabel(self.groupBox)
        self.lblSalt.setMaximumSize(QtCore.QSize(132, 16777215))
        self.lblSalt.setFont(font)
        self.lblSalt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblSalt.setAutoFillBackground(False)
        self.lblSalt.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblSalt.setLineWidth(0)
        self.lblSalt.setScaledContents(True)
        self.lblSalt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSalt.setWordWrap(False)
        self.lblSalt.setIndent(-1)
        self.lblSalt.setObjectName("lblSalt")
        self.gridLayout_3.addWidget(self.lblSalt, 5, 0, 1, 1)
        self.lblSaltVal = QtWidgets.QLabel(self.groupBox)
        self.lblSaltVal.setFont(font)
        self.lblSaltVal.setAutoFillBackground(False)
        self.lblSaltVal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblSaltVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSaltVal.setObjectName("lblSaltVal")
        self.gridLayout_3.addWidget(self.lblSaltVal, 5, 1, 1, 1)
        # set 'Scan', 'Incorrect Item?', 'Add to daily intake', Back' and 'Tare' buttons
        self.btnBack = QtWidgets.QPushButton(self.centralWidget)
        self.btnBack.setMinimumSize(QtCore.QSize(158, 32))
        self.btnBack.setMaximumSize(QtCore.QSize(158, 32))
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 9, 6, 2, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 0, 11, 11)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblObject = QtWidgets.QLabel(self.centralWidget)
        self.btnScan = QtWidgets.QPushButton(self.centralWidget)
        self.btnScan.setEnabled(True)
        self.btnScan.setMinimumSize(QtCore.QSize(158, 32))
        self.btnScan.setMaximumSize(QtCore.QSize(158, 32))
        self.btnScan.setFont(font)
        self.btnScan.resize(self.btnScan.sizeHint())
        self.btnScan.setObjectName("btnScan")
        #self.gridLayout.addWidget(self.btnScan, 3, 0, 1, 1)
        self.btnIncorrectItem = QtWidgets.QPushButton(self.centralWidget)
        self.btnIncorrectItem.setEnabled(True)
        self.btnIncorrectItem.setMinimumSize(QtCore.QSize(158, 32))
        self.btnIncorrectItem.setMaximumSize(QtCore.QSize(158, 32))
        self.btnIncorrectItem.setFont(font)
        self.btnIncorrectItem.setObjectName("btnIncorrectItem")
        #self.gridLayout.addWidget(self.btnIncorrectItem, 3, 1, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(self.centralWidget)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAdd.setMaximumSize(QtCore.QSize(158, 32))
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 7, 6, 2, 2)
        self.btnTare = QtWidgets.QPushButton(self.centralWidget)
        self.btnTare.setMinimumSize(QtCore.QSize(158, 32))
        self.btnTare.setMaximumSize(QtCore.QSize(158, 32))
        self.btnTare.setFont(font)
        self.btnTare.setObjectName("btnTare")
        #self.gridLayout.addWidget(self.btnTare, 5, 1, 1, 1)
        self.imgFoodItem = QtWidgets.QGraphicsView(self.centralWidget)
        self.imgFoodItem.setMinimumSize(QtCore.QSize(360, 240))
        # set 'Place food item on the scale'
        font.setPointSize(14)
        font.setBold(True)
        self.lblTitle = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 0, 0, 1, 6)
        # show predicted food image
        self.imgFoodItem.setFont(font)
        self.imgFoodItem.setObjectName("imgFoodItem")
        self.gridLayout.addWidget(self.imgFoodItem, 1, 0, 5, 6)
        getWeight.setCentralWidget(self.centralWidget)
        #
        self.retranslateUi(getWeight)
        QtCore.QMetaObject.connectSlotsByName(getWeight)
        self.show()

    def retranslateUi(self, getWeight):
        _translate = QtCore.QCoreApplication.translate
        getWeight.setWindowTitle(_translate("getWeight", "smartScaleGUI"))
        self.lblGrams.setText(_translate("getWeight", "g"))
        self.groupBox.setTitle(_translate("getWeight", "Nutritional Information"))
        self.lblSalt.setText(_translate("getWeight", "Salt (g)"))
        self.lblProteinVal.setText(_translate("getWeight", "lblProteinVal"))
        self.lblSugarVal.setText(_translate("getWeight", "lblSugarVal"))
        self.lblFat.setText(_translate("getWeight", "Fat (g)"))
        self.lblSaltVal.setText(_translate("getWeight", "lbSaltVal"))
        self.lblFbreVal.setText(_translate("getWeight", "lblFibreVal"))
        self.lblSugar.setText(_translate("getWeight", "Sugar (g)"))
        self.lblFibre.setText(_translate("getWeight", "Fibre (g)"))
        self.lblFatVal.setText(_translate("getWeight", "lblFatVal"))
        self.lblProtein.setText(_translate("getWeight", "Protein (g)"))
        self.lblEnergy.setText(_translate("getWeight", "Energy value (kcal)"))
        self.lblEnergyVal.setText(_translate("getWeight", "lblEnergyVal"))
        self.btnBack.setText(_translate("getWeight", "Back"))
        self.btnScan.setText(_translate("getWeight", "Scan"))
        self.btnIncorrectItem.setText(_translate("getWeight", "Incorrect Item?"))
        self.btnAdd.setText(_translate("getWeight", "Add to daily intake"))
        self.lblTitle.setText(_translate("getWeight", "Place food item on the scale"))
        self.btnTare.setText(_translate("getWeight", "Tare"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = Ui_getWeight()
    sys.exit(app.exec())
