# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userDetailChange.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userDetailChange(object):
    def setupUi(self, userDetailChange):
        userDetailChange.setObjectName("userDetailChange")
        userDetailChange.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(userDetailChange)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout.addWidget(self.lblStatus, 0, 2, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.centralWidget)
        self.btnCancel.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 2, 0, 1, 1)
        self.btnSubmitChanges = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubmitChanges.sizePolicy().hasHeightForWidth())
        self.btnSubmitChanges.setSizePolicy(sizePolicy)
        self.btnSubmitChanges.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnSubmitChanges.setFont(font)
        self.btnSubmitChanges.setObjectName("btnSubmitChanges")
        self.gridLayout.addWidget(self.btnSubmitChanges, 2, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblPassword = QtWidgets.QLabel(self.centralWidget)
        self.lblPassword.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblPassword.setFont(font)
        self.lblPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtPassword)
        self.lblEmail = QtWidgets.QLabel(self.centralWidget)
        self.lblEmail.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblEmail.setFont(font)
        self.lblEmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtEmail.setFont(font)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtEmail)
        self.lblFirstname = QtWidgets.QLabel(self.centralWidget)
        self.lblFirstname.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblFirstname.setFont(font)
        self.lblFirstname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFirstname.setObjectName("lblFirstname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblFirstname)
        self.txtFirstname = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtFirstname.setFont(font)
        self.txtFirstname.setObjectName("txtFirstname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtFirstname)
        self.lblLastname = QtWidgets.QLabel(self.centralWidget)
        self.lblLastname.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblLastname.setFont(font)
        self.lblLastname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLastname.setObjectName("lblLastname")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblLastname)
        self.txtLastname = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtLastname.setFont(font)
        self.txtLastname.setObjectName("txtLastname")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtLastname)
        self.lblDoB = QtWidgets.QLabel(self.centralWidget)
        self.lblDoB.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblDoB.setFont(font)
        self.lblDoB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDoB.setObjectName("lblDoB")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblDoB)
        self.datDoB = QtWidgets.QDateEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.datDoB.setFont(font)
        self.datDoB.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.datDoB.setCalendarPopup(True)
        self.datDoB.setObjectName("datDoB")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.datDoB)
        self.lblGender = QtWidgets.QLabel(self.centralWidget)
        self.lblGender.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblGender.setFont(font)
        self.lblGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGender.setObjectName("lblGender")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblGender)
        self.rbnMale = QtWidgets.QRadioButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.rbnMale.setFont(font)
        self.rbnMale.setObjectName("rbnMale")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rbnMale)
        self.rbnFemale = QtWidgets.QRadioButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.rbnFemale.setFont(font)
        self.rbnFemale.setObjectName("rbnFemale")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rbnFemale)
        self.lblHeight = QtWidgets.QLabel(self.centralWidget)
        self.lblHeight.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblHeight.setFont(font)
        self.lblHeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblHeight.setObjectName("lblHeight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblHeight)
        self.txtHeight = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtHeight.setFont(font)
        self.txtHeight.setObjectName("txtHeight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtHeight)
        self.lblWeight = QtWidgets.QLabel(self.centralWidget)
        self.lblWeight.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblWeight.setFont(font)
        self.lblWeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblWeight.setObjectName("lblWeight")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lblWeight)
        self.txtWeight = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.txtWeight.setFont(font)
        self.txtWeight.setObjectName("txtWeight")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txtWeight)
        self.lblExpressLogin = QtWidgets.QLabel(self.centralWidget)
        self.lblExpressLogin.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblExpressLogin.setFont(font)
        self.lblExpressLogin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblExpressLogin.setObjectName("lblExpressLogin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lblExpressLogin)
        self.chkExpressLogin = QtWidgets.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.chkExpressLogin.setFont(font)
        self.chkExpressLogin.setObjectName("chkExpressLogin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.chkExpressLogin)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 3)
        self.lblTitle = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(13)
        self.lblTitle.setFont(font)
        self.lblTitle.setIndent(0)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 0, 0, 1, 2)
        userDetailChange.setCentralWidget(self.centralWidget)

        self.retranslateUi(userDetailChange)
        QtCore.QMetaObject.connectSlotsByName(userDetailChange)
        userDetailChange.setTabOrder(self.txtPassword, self.txtEmail)
        userDetailChange.setTabOrder(self.txtEmail, self.txtFirstname)
        userDetailChange.setTabOrder(self.txtFirstname, self.txtLastname)
        userDetailChange.setTabOrder(self.txtLastname, self.datDoB)
        userDetailChange.setTabOrder(self.datDoB, self.rbnMale)
        userDetailChange.setTabOrder(self.rbnMale, self.rbnFemale)
        userDetailChange.setTabOrder(self.rbnFemale, self.txtHeight)
        userDetailChange.setTabOrder(self.txtHeight, self.txtWeight)
        userDetailChange.setTabOrder(self.txtWeight, self.chkExpressLogin)
        userDetailChange.setTabOrder(self.chkExpressLogin, self.btnSubmitChanges)
        userDetailChange.setTabOrder(self.btnSubmitChanges, self.btnCancel)

    def retranslateUi(self, userDetailChange):
        _translate = QtCore.QCoreApplication.translate
        userDetailChange.setWindowTitle(_translate("userDetailChange", "smartScaleGUI"))
        self.btnCancel.setText(_translate("userDetailChange", "Cancel"))
        self.btnSubmitChanges.setText(_translate("userDetailChange", "Submit Changes"))
        self.lblPassword.setText(_translate("userDetailChange", "Current Password :"))
        self.lblEmail.setText(_translate("userDetailChange", "Email :"))
        self.lblFirstname.setText(_translate("userDetailChange", "Firstname :"))
        self.lblLastname.setText(_translate("userDetailChange", "Lastname :"))
        self.lblDoB.setText(_translate("userDetailChange", "Date of Birth :"))
        self.datDoB.setDisplayFormat(_translate("userDetailChange", "dd-MMM-yyyy"))
        self.lblGender.setText(_translate("userDetailChange", "Gender :"))
        self.rbnMale.setText(_translate("userDetailChange", "Male"))
        self.rbnFemale.setText(_translate("userDetailChange", "Female"))
        self.lblHeight.setText(_translate("userDetailChange", "Height (cm) :"))
        self.lblWeight.setText(_translate("userDetailChange", "Weight (kg) :"))
        self.lblExpressLogin.setText(_translate("userDetailChange", "Expressed Login: :"))
        self.chkExpressLogin.setText(_translate("userDetailChange", "Activated"))
        self.lblTitle.setText(_translate("userDetailChange", "Please enter the following details : "))

