# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userPasswordChange.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userPasswordChange(object):
    def setupUi(self, userPasswordChange):
        userPasswordChange.setObjectName("userPasswordChange")
        userPasswordChange.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(userPasswordChange)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitle = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblOldPassword = QtWidgets.QLabel(self.centralWidget)
        self.lblOldPassword.setObjectName("lblOldPassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblOldPassword)
        self.txtOldPassword = QtWidgets.QLineEdit(self.centralWidget)
        self.txtOldPassword.setMinimumSize(QtCore.QSize(469, 0))
        self.txtOldPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtOldPassword.setObjectName("txtOldPassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtOldPassword)
        self.lblNewPassword = QtWidgets.QLabel(self.centralWidget)
        self.lblNewPassword.setObjectName("lblNewPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblNewPassword)
        self.txtNewPassword = QtWidgets.QLineEdit(self.centralWidget)
        self.txtNewPassword.setMinimumSize(QtCore.QSize(469, 0))
        self.txtNewPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.txtNewPassword.setInputMask("")
        self.txtNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNewPassword.setObjectName("txtNewPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtNewPassword)
        self.lblComfirmPassword = QtWidgets.QLabel(self.centralWidget)
        self.lblComfirmPassword.setObjectName("lblComfirmPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblComfirmPassword)
        self.txtConfirmPassword = QtWidgets.QLineEdit(self.centralWidget)
        self.txtConfirmPassword.setMinimumSize(QtCore.QSize(469, 0))
        self.txtConfirmPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.txtConfirmPassword.setInputMask("")
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtConfirmPassword)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout_2.addWidget(self.lblStatus, 0, 2, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_2.addWidget(self.btnCancel, 1, 0, 1, 1)
        self.btnChangePassword = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChangePassword.sizePolicy().hasHeightForWidth())
        self.btnChangePassword.setSizePolicy(sizePolicy)
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.gridLayout_2.addWidget(self.btnChangePassword, 1, 1, 1, 2)
        userPasswordChange.setCentralWidget(self.centralWidget)

        self.retranslateUi(userPasswordChange)
        QtCore.QMetaObject.connectSlotsByName(userPasswordChange)

    def retranslateUi(self, userPasswordChange):
        _translate = QtCore.QCoreApplication.translate
        userPasswordChange.setWindowTitle(_translate("userPasswordChange", "smartScaleGUI"))
        self.lblTitle.setText(_translate("userPasswordChange", "Please enter the following :"))
        self.lblOldPassword.setText(_translate("userPasswordChange", "Old Passwod :"))
        self.lblNewPassword.setText(_translate("userPasswordChange", "New Password :"))
        self.lblComfirmPassword.setText(_translate("userPasswordChange", "Comfirm Password :"))
        self.btnCancel.setText(_translate("userPasswordChange", "Cancel"))
        self.btnChangePassword.setText(_translate("userPasswordChange", "Change Password"))

