# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'foodsuggestionmenu.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_foodSuggestionMenu(object):
    def setupUi(self, foodSuggestionMenu):
        foodSuggestionMenu.setObjectName("foodSuggestionMenu")
        foodSuggestionMenu.resize(805, 488)
        self.gridLayout = QtWidgets.QGridLayout(foodSuggestionMenu)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_title = QtWidgets.QLabel(foodSuggestionMenu)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout.addWidget(self.lbl_title, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(foodSuggestionMenu)
        self.scrollArea.setMinimumSize(QtCore.QSize(781, 321))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 334))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(779, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_item5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_item5.setMinimumSize(QtCore.QSize(250, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_item5.setFont(font)
        self.btn_item5.setObjectName("btn_item5")
        self.gridLayout_3.addWidget(self.btn_item5, 1, 1, 1, 1)
        self.btn_item4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_item4.setMinimumSize(QtCore.QSize(250, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_item4.setFont(font)
        self.btn_item4.setObjectName("btn_item4")
        self.gridLayout_3.addWidget(self.btn_item4, 1, 0, 1, 1)
        self.btn_item6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_item6.setMinimumSize(QtCore.QSize(250, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_item6.setFont(font)
        self.btn_item6.setObjectName("btn_item6")
        self.gridLayout_3.addWidget(self.btn_item6, 1, 2, 1, 1)
        self.btn_item2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_item2.setMinimumSize(QtCore.QSize(250, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_item2.setFont(font)
        self.btn_item2.setObjectName("btn_item2")
        self.gridLayout_3.addWidget(self.btn_item2, 0, 1, 1, 1)
        self.btn_item3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_item3.setMinimumSize(QtCore.QSize(250, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_item3.setFont(font)
        self.btn_item3.setObjectName("btn_item3")
        self.gridLayout_3.addWidget(self.btn_item3, 0, 2, 1, 1)
        self.btn_item1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_item1.setMinimumSize(QtCore.QSize(250, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_item1.setFont(font)
        self.btn_item1.setObjectName("btn_item1")
        self.gridLayout_3.addWidget(self.btn_item1, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back = QtWidgets.QPushButton(foodSuggestionMenu)
        self.btn_back.setMinimumSize(QtCore.QSize(151, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        spacerItem = QtWidgets.QSpacerItem(458, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_notFound = QtWidgets.QPushButton(foodSuggestionMenu)
        self.btn_notFound.setMinimumSize(QtCore.QSize(151, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_notFound.setFont(font)
        self.btn_notFound.setObjectName("btn_notFound")
        self.horizontalLayout.addWidget(self.btn_notFound)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(foodSuggestionMenu)
        QtCore.QMetaObject.connectSlotsByName(foodSuggestionMenu)

    def retranslateUi(self, foodSuggestionMenu):
        _translate = QtCore.QCoreApplication.translate
        foodSuggestionMenu.setWindowTitle(_translate("foodSuggestionMenu", "foodSuggestionMenu"))
        self.lbl_title.setText(_translate("foodSuggestionMenu", "Our suggested food items:"))
        self.btn_item5.setText(_translate("foodSuggestionMenu", "Item 5"))
        self.btn_item4.setText(_translate("foodSuggestionMenu", "Item 4"))
        self.btn_item6.setText(_translate("foodSuggestionMenu", "Item 6"))
        self.btn_item2.setText(_translate("foodSuggestionMenu", "Item 2"))
        self.btn_item3.setText(_translate("foodSuggestionMenu", "Item 3"))
        self.btn_item1.setText(_translate("foodSuggestionMenu", "Item 1"))
        self.btn_back.setText(_translate("foodSuggestionMenu", "Back"))
        self.btn_notFound.setText(_translate("foodSuggestionMenu", "Not found?"))

