# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textInput.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_textInput(object):
    def setupUi(self, textInput):
        textInput.setObjectName("textInput")
        textInput.resize(800, 480)
        font = QtGui.QFont()
        font.setPointSize(11)
        textInput.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(textInput)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_login = QtWidgets.QPushButton(textInput)
        self.btn_login.setMinimumSize(QtCore.QSize(141, 70))
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 2, 2, 1, 1)
        self.btn_back = QtWidgets.QPushButton(textInput)
        self.btn_back.setMinimumSize(QtCore.QSize(141, 70))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(487, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(textInput)
        self.groupBox.setMinimumSize(QtCore.QSize(741, 331))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lbl_currentText = QtWidgets.QLabel(self.groupBox)
        self.lbl_currentText.setGeometry(QtCore.QRect(15, 15, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_currentText.sizePolicy().hasHeightForWidth())
        self.lbl_currentText.setSizePolicy(sizePolicy)
        self.lbl_currentText.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_currentText.setText("")
        self.lbl_currentText.setObjectName("lbl_currentText")
        self.lineEdit_currentText = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_currentText.setGeometry(QtCore.QRect(103, 5, 651, 41))
        self.lineEdit_currentText.setMinimumSize(QtCore.QSize(513, 19))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_currentText.setFont(font)
        self.lineEdit_currentText.setObjectName("lineEdit_currentText")
        self.keyboard = QtWidgets.QFrame(self.groupBox)
        self.keyboard.setGeometry(QtCore.QRect(0, 50, 771, 281))
        self.keyboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyboard.setObjectName("keyboard")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.keyboard)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.row1 = QtWidgets.QHBoxLayout()
        self.row1.setContentsMargins(11, 11, 11, 11)
        self.row1.setSpacing(6)
        self.row1.setObjectName("row1")
        self.Q = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q.sizePolicy().hasHeightForWidth())
        self.Q.setSizePolicy(sizePolicy)
        self.Q.setMinimumSize(QtCore.QSize(46, 55))
        self.Q.setObjectName("Q")
        self.row1.addWidget(self.Q)
        self.W = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.W.sizePolicy().hasHeightForWidth())
        self.W.setSizePolicy(sizePolicy)
        self.W.setMinimumSize(QtCore.QSize(46, 55))
        self.W.setObjectName("W")
        self.row1.addWidget(self.W)
        self.E = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E.sizePolicy().hasHeightForWidth())
        self.E.setSizePolicy(sizePolicy)
        self.E.setMinimumSize(QtCore.QSize(46, 55))
        self.E.setObjectName("E")
        self.row1.addWidget(self.E)
        self.R = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R.sizePolicy().hasHeightForWidth())
        self.R.setSizePolicy(sizePolicy)
        self.R.setMinimumSize(QtCore.QSize(46, 55))
        self.R.setObjectName("R")
        self.row1.addWidget(self.R)
        self.T = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T.sizePolicy().hasHeightForWidth())
        self.T.setSizePolicy(sizePolicy)
        self.T.setMinimumSize(QtCore.QSize(46, 55))
        self.T.setObjectName("T")
        self.row1.addWidget(self.T)
        self.Y = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y.sizePolicy().hasHeightForWidth())
        self.Y.setSizePolicy(sizePolicy)
        self.Y.setMinimumSize(QtCore.QSize(46, 55))
        self.Y.setObjectName("Y")
        self.row1.addWidget(self.Y)
        self.U = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U.sizePolicy().hasHeightForWidth())
        self.U.setSizePolicy(sizePolicy)
        self.U.setMinimumSize(QtCore.QSize(46, 55))
        self.U.setObjectName("U")
        self.row1.addWidget(self.U)
        self.I = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.I.sizePolicy().hasHeightForWidth())
        self.I.setSizePolicy(sizePolicy)
        self.I.setMinimumSize(QtCore.QSize(46, 55))
        self.I.setObjectName("I")
        self.row1.addWidget(self.I)
        self.O = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O.sizePolicy().hasHeightForWidth())
        self.O.setSizePolicy(sizePolicy)
        self.O.setMinimumSize(QtCore.QSize(46, 55))
        self.O.setObjectName("O")
        self.row1.addWidget(self.O)
        self.P = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P.sizePolicy().hasHeightForWidth())
        self.P.setSizePolicy(sizePolicy)
        self.P.setMinimumSize(QtCore.QSize(46, 55))
        self.P.setObjectName("P")
        self.row1.addWidget(self.P)
        self.verticalLayout.addLayout(self.row1)
        self.row2 = QtWidgets.QHBoxLayout()
        self.row2.setContentsMargins(11, 11, 11, 11)
        self.row2.setSpacing(6)
        self.row2.setObjectName("row2")
        spacerItem1 = QtWidgets.QSpacerItem(55, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem1)
        self.A = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A.sizePolicy().hasHeightForWidth())
        self.A.setSizePolicy(sizePolicy)
        self.A.setMinimumSize(QtCore.QSize(46, 55))
        self.A.setObjectName("A")
        self.row2.addWidget(self.A)
        self.S = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S.sizePolicy().hasHeightForWidth())
        self.S.setSizePolicy(sizePolicy)
        self.S.setMinimumSize(QtCore.QSize(46, 55))
        self.S.setObjectName("S")
        self.row2.addWidget(self.S)
        self.D = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D.sizePolicy().hasHeightForWidth())
        self.D.setSizePolicy(sizePolicy)
        self.D.setMinimumSize(QtCore.QSize(46, 55))
        self.D.setObjectName("D")
        self.row2.addWidget(self.D)
        self.F = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F.sizePolicy().hasHeightForWidth())
        self.F.setSizePolicy(sizePolicy)
        self.F.setMinimumSize(QtCore.QSize(46, 55))
        self.F.setObjectName("F")
        self.row2.addWidget(self.F)
        self.G = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G.sizePolicy().hasHeightForWidth())
        self.G.setSizePolicy(sizePolicy)
        self.G.setMinimumSize(QtCore.QSize(46, 55))
        self.G.setObjectName("G")
        self.row2.addWidget(self.G)
        self.H = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H.sizePolicy().hasHeightForWidth())
        self.H.setSizePolicy(sizePolicy)
        self.H.setMinimumSize(QtCore.QSize(46, 55))
        self.H.setObjectName("H")
        self.row2.addWidget(self.H)
        self.J = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.J.sizePolicy().hasHeightForWidth())
        self.J.setSizePolicy(sizePolicy)
        self.J.setMinimumSize(QtCore.QSize(46, 55))
        self.J.setObjectName("J")
        self.row2.addWidget(self.J)
        self.K = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K.sizePolicy().hasHeightForWidth())
        self.K.setSizePolicy(sizePolicy)
        self.K.setMinimumSize(QtCore.QSize(46, 55))
        self.K.setObjectName("K")
        self.row2.addWidget(self.K)
        self.L = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L.sizePolicy().hasHeightForWidth())
        self.L.setSizePolicy(sizePolicy)
        self.L.setMinimumSize(QtCore.QSize(46, 55))
        self.L.setObjectName("L")
        self.row2.addWidget(self.L)
        spacerItem2 = QtWidgets.QSpacerItem(55, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.row2)
        self.row3 = QtWidgets.QHBoxLayout()
        self.row3.setContentsMargins(11, 11, 11, 11)
        self.row3.setSpacing(6)
        self.row3.setObjectName("row3")
        self.btnShift = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShift.sizePolicy().hasHeightForWidth())
        self.btnShift.setSizePolicy(sizePolicy)
        self.btnShift.setMinimumSize(QtCore.QSize(50, 55))
        self.btnShift.setObjectName("btnShift")
        self.row3.addWidget(self.btnShift)
        spacerItem3 = QtWidgets.QSpacerItem(0, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.row3.addItem(spacerItem3)
        self.Z = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Z.sizePolicy().hasHeightForWidth())
        self.Z.setSizePolicy(sizePolicy)
        self.Z.setMinimumSize(QtCore.QSize(46, 55))
        self.Z.setObjectName("Z")
        self.row3.addWidget(self.Z)
        self.X = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X.sizePolicy().hasHeightForWidth())
        self.X.setSizePolicy(sizePolicy)
        self.X.setMinimumSize(QtCore.QSize(46, 55))
        self.X.setObjectName("X")
        self.row3.addWidget(self.X)
        self.C = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C.sizePolicy().hasHeightForWidth())
        self.C.setSizePolicy(sizePolicy)
        self.C.setMinimumSize(QtCore.QSize(46, 55))
        self.C.setObjectName("C")
        self.row3.addWidget(self.C)
        self.V = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.V.sizePolicy().hasHeightForWidth())
        self.V.setSizePolicy(sizePolicy)
        self.V.setMinimumSize(QtCore.QSize(46, 55))
        self.V.setObjectName("V")
        self.row3.addWidget(self.V)
        self.B = QtWidgets.QPushButton(self.keyboard)
        self.B.setMinimumSize(QtCore.QSize(46, 55))
        self.B.setObjectName("B")
        self.row3.addWidget(self.B)
        self.N = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N.sizePolicy().hasHeightForWidth())
        self.N.setSizePolicy(sizePolicy)
        self.N.setMinimumSize(QtCore.QSize(46, 55))
        self.N.setObjectName("N")
        self.row3.addWidget(self.N)
        self.M = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M.sizePolicy().hasHeightForWidth())
        self.M.setSizePolicy(sizePolicy)
        self.M.setMinimumSize(QtCore.QSize(46, 55))
        self.M.setObjectName("M")
        self.row3.addWidget(self.M)
        spacerItem4 = QtWidgets.QSpacerItem(10, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.row3.addItem(spacerItem4)
        self.btnDel = QtWidgets.QPushButton(self.keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDel.sizePolicy().hasHeightForWidth())
        self.btnDel.setSizePolicy(sizePolicy)
        self.btnDel.setMinimumSize(QtCore.QSize(70, 55))
        self.btnDel.setObjectName("btnDel")
        self.row3.addWidget(self.btnDel)
        self.verticalLayout.addLayout(self.row3)
        self.row4 = QtWidgets.QHBoxLayout()
        self.row4.setContentsMargins(11, 11, 11, 11)
        self.row4.setSpacing(6)
        self.row4.setObjectName("row4")
        self.btnToggle = QtWidgets.QPushButton(self.keyboard)
        self.btnToggle.setMinimumSize(QtCore.QSize(100, 55))
        self.btnToggle.setObjectName("btnToggle")
        self.row4.addWidget(self.btnToggle)
        self.space = QtWidgets.QPushButton(self.keyboard)
        self.space.setMinimumSize(QtCore.QSize(450, 55))
        self.space.setObjectName("space")
        self.row4.addWidget(self.space)
        self.btnAt = QtWidgets.QPushButton(self.keyboard)
        self.btnAt.setMinimumSize(QtCore.QSize(46, 55))
        self.btnAt.setObjectName("btnAt")
        self.row4.addWidget(self.btnAt)
        self.btnDot = QtWidgets.QPushButton(self.keyboard)
        self.btnDot.setMinimumSize(QtCore.QSize(46, 55))
        self.btnDot.setObjectName("btnDot")
        self.row4.addWidget(self.btnDot)
        self.verticalLayout.addLayout(self.row4)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 3)
        self.lbl_title = QtWidgets.QLabel(textInput)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout.addWidget(self.lbl_title, 0, 0, 1, 3)

        self.retranslateUi(textInput)
        QtCore.QMetaObject.connectSlotsByName(textInput)

    def retranslateUi(self, textInput):
        _translate = QtCore.QCoreApplication.translate
        textInput.setWindowTitle(_translate("textInput", "newLogin"))
        self.btn_login.setText(_translate("textInput", "Login"))
        self.btn_back.setText(_translate("textInput", "Back"))
        self.Q.setText(_translate("textInput", "Q"))
        self.W.setText(_translate("textInput", "W"))
        self.E.setText(_translate("textInput", "E"))
        self.R.setText(_translate("textInput", "R"))
        self.T.setText(_translate("textInput", "T"))
        self.Y.setText(_translate("textInput", "Y"))
        self.U.setText(_translate("textInput", "U"))
        self.I.setText(_translate("textInput", "I"))
        self.O.setText(_translate("textInput", "O"))
        self.P.setText(_translate("textInput", "P"))
        self.A.setText(_translate("textInput", "A"))
        self.S.setText(_translate("textInput", "S"))
        self.D.setText(_translate("textInput", "D"))
        self.F.setText(_translate("textInput", "F"))
        self.G.setText(_translate("textInput", "G"))
        self.H.setText(_translate("textInput", "H"))
        self.J.setText(_translate("textInput", "J"))
        self.K.setText(_translate("textInput", "K"))
        self.L.setText(_translate("textInput", "L"))
        self.btnShift.setText(_translate("textInput", "Shift"))
        self.Z.setText(_translate("textInput", "Z"))
        self.X.setText(_translate("textInput", "X"))
        self.C.setText(_translate("textInput", "C"))
        self.V.setText(_translate("textInput", "V"))
        self.B.setText(_translate("textInput", "B"))
        self.N.setText(_translate("textInput", "N"))
        self.M.setText(_translate("textInput", "M"))
        self.btnDel.setText(_translate("textInput", "Del"))
        self.btnToggle.setText(_translate("textInput", "123"))
        self.space.setText(_translate("textInput", "Space"))
        self.btnAt.setText(_translate("textInput", "@"))
        self.btnDot.setText(_translate("textInput", "."))
        self.lbl_title.setText(_translate("textInput", "-"))

