# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passcode.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_passCode(object):
    def setupUi(self, passCode):
        passCode.setObjectName("passCode")
        passCode.resize(800, 480)
        self.gridLayout = QtWidgets.QGridLayout(passCode)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_title = QtWidgets.QLabel(passCode)
        self.lbl_title.setMinimumSize(QtCore.QSize(201, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout_4.addWidget(self.lbl_title)
        spacerItem = QtWidgets.QSpacerItem(548, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 2, 4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lbl_info = QtWidgets.QLabel(passCode)
        self.lbl_info.setObjectName("lbl_info")
        self.horizontalLayout_3.addWidget(self.lbl_info)
        spacerItem2 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(191, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lineEdit_num = QtWidgets.QLineEdit(passCode)
        self.lineEdit_num.setMinimumSize(QtCore.QSize(351, 75))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.lineEdit_num.setFont(font)
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.horizontalLayout.addWidget(self.lineEdit_num)
        spacerItem4 = QtWidgets.QSpacerItem(211, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 4)
        spacerItem5 = QtWidgets.QSpacerItem(43, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 2)
        self.frame = QtWidgets.QFrame(passCode)
        self.frame.setMinimumSize(QtCore.QSize(491, 311))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.three = QtWidgets.QPushButton(self.frame)
        self.three.setGeometry(QtCore.QRect(324, 9, 158, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.three.sizePolicy().hasHeightForWidth())
        self.three.setSizePolicy(sizePolicy)
        self.three.setMinimumSize(QtCore.QSize(158, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.four = QtWidgets.QPushButton(self.frame)
        self.four.setGeometry(QtCore.QRect(7, 83, 158, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.four.sizePolicy().hasHeightForWidth())
        self.four.setSizePolicy(sizePolicy)
        self.four.setMinimumSize(QtCore.QSize(158, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.frame)
        self.five.setGeometry(QtCore.QRect(165, 83, 157, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.five.sizePolicy().hasHeightForWidth())
        self.five.setSizePolicy(sizePolicy)
        self.five.setMinimumSize(QtCore.QSize(157, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.frame)
        self.six.setGeometry(QtCore.QRect(324, 83, 158, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.six.sizePolicy().hasHeightForWidth())
        self.six.setSizePolicy(sizePolicy)
        self.six.setMinimumSize(QtCore.QSize(158, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.seven = QtWidgets.QPushButton(self.frame)
        self.seven.setGeometry(QtCore.QRect(7, 157, 158, 72))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seven.sizePolicy().hasHeightForWidth())
        self.seven.setSizePolicy(sizePolicy)
        self.seven.setMinimumSize(QtCore.QSize(158, 72))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.frame)
        self.eight.setGeometry(QtCore.QRect(165, 157, 157, 72))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eight.sizePolicy().hasHeightForWidth())
        self.eight.setSizePolicy(sizePolicy)
        self.eight.setMinimumSize(QtCore.QSize(157, 72))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.frame)
        self.nine.setGeometry(QtCore.QRect(324, 157, 158, 72))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nine.sizePolicy().hasHeightForWidth())
        self.nine.setSizePolicy(sizePolicy)
        self.nine.setMinimumSize(QtCore.QSize(158, 72))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.btn_black = QtWidgets.QPushButton(self.frame)
        self.btn_black.setGeometry(QtCore.QRect(7, 230, 158, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_black.sizePolicy().hasHeightForWidth())
        self.btn_black.setSizePolicy(sizePolicy)
        self.btn_black.setMinimumSize(QtCore.QSize(158, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_black.setFont(font)
        self.btn_black.setText("")
        self.btn_black.setObjectName("btn_black")
        self.zero = QtWidgets.QPushButton(self.frame)
        self.zero.setGeometry(QtCore.QRect(165, 230, 157, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero.sizePolicy().hasHeightForWidth())
        self.zero.setSizePolicy(sizePolicy)
        self.zero.setMinimumSize(QtCore.QSize(157, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.btn_del = QtWidgets.QPushButton(self.frame)
        self.btn_del.setGeometry(QtCore.QRect(324, 230, 158, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del.sizePolicy().hasHeightForWidth())
        self.btn_del.setSizePolicy(sizePolicy)
        self.btn_del.setMinimumSize(QtCore.QSize(158, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_del.setFont(font)
        self.btn_del.setObjectName("btn_del")
        self.one = QtWidgets.QPushButton(self.frame)
        self.one.setGeometry(QtCore.QRect(7, 9, 158, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one.sizePolicy().hasHeightForWidth())
        self.one.setSizePolicy(sizePolicy)
        self.one.setMinimumSize(QtCore.QSize(158, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.frame)
        self.two.setGeometry(QtCore.QRect(165, 9, 157, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.two.sizePolicy().hasHeightForWidth())
        self.two.setSizePolicy(sizePolicy)
        self.two.setMinimumSize(QtCore.QSize(157, 73))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.frame, 3, 2, 3, 1)
        self.btn_forgot = QtWidgets.QPushButton(passCode)
        self.btn_forgot.setMinimumSize(QtCore.QSize(121, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_forgot.setFont(font)
        self.btn_forgot.setObjectName("btn_forgot")
        self.gridLayout.addWidget(self.btn_forgot, 3, 3, 1, 1)
        self.btn_done = QtWidgets.QPushButton(passCode)
        self.btn_done.setMinimumSize(QtCore.QSize(121, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_done.setFont(font)
        self.btn_done.setObjectName("btn_done")
        self.gridLayout.addWidget(self.btn_done, 4, 3, 1, 1)
        self.btn_back = QtWidgets.QPushButton(passCode)
        self.btn_back.setMinimumSize(QtCore.QSize(121, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 5, 3, 1, 1)
        self.frame.raise_()
        self.btn_back.raise_()
        self.btn_done.raise_()
        self.btn_forgot.raise_()

        self.retranslateUi(passCode)
        QtCore.QMetaObject.connectSlotsByName(passCode)

    def retranslateUi(self, passCode):
        _translate = QtCore.QCoreApplication.translate
        passCode.setWindowTitle(_translate("passCode", "passCode"))
        self.lbl_title.setText(_translate("passCode", "Passcode"))
        self.lbl_info.setText(_translate("passCode", "TextLabel"))
        self.three.setText(_translate("passCode", "3"))
        self.four.setText(_translate("passCode", "4"))
        self.five.setText(_translate("passCode", "5"))
        self.six.setText(_translate("passCode", "6"))
        self.seven.setText(_translate("passCode", "7"))
        self.eight.setText(_translate("passCode", "8"))
        self.nine.setText(_translate("passCode", "9"))
        self.zero.setText(_translate("passCode", "0"))
        self.btn_del.setText(_translate("passCode", "Del"))
        self.one.setText(_translate("passCode", "1"))
        self.two.setText(_translate("passCode", "2"))
        self.btn_forgot.setText(_translate("passCode", "Forgot Passcode?"))
        self.btn_done.setText(_translate("passCode", "Done"))
        self.btn_back.setText(_translate("passCode", "Back"))

