# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(800, 480)
        self.gridLayout = QtWidgets.QGridLayout(mainMenu)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_title = QtWidgets.QLabel(mainMenu)
        self.lbl_title.setMinimumSize(QtCore.QSize(341, 20))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout.addWidget(self.lbl_title)
        spacerItem = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_update = QtWidgets.QPushButton(mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update.sizePolicy().hasHeightForWidth())
        self.btn_update.setSizePolicy(sizePolicy)
        self.btn_update.setMinimumSize(QtCore.QSize(165, 80))
        self.btn_update.setMaximumSize(QtCore.QSize(16777215, 100))
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout.addWidget(self.btn_update)
        self.btn_close = QtWidgets.QPushButton(mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(165, 80))
        self.btn_close.setMaximumSize(QtCore.QSize(16777215, 100))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.btn_login = QtWidgets.QPushButton(mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 1, 0, 1, 1)
        self.btn_guest = QtWidgets.QPushButton(mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_guest.sizePolicy().hasHeightForWidth())
        self.btn_guest.setSizePolicy(sizePolicy)
        self.btn_guest.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_guest.setFont(font)
        self.btn_guest.setObjectName("btn_guest")
        self.gridLayout.addWidget(self.btn_guest, 1, 1, 1, 1)
        self.btn_scaleOnly = QtWidgets.QPushButton(mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_scaleOnly.sizePolicy().hasHeightForWidth())
        self.btn_scaleOnly.setSizePolicy(sizePolicy)
        self.btn_scaleOnly.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_scaleOnly.setFont(font)
        self.btn_scaleOnly.setObjectName("btn_scaleOnly")
        self.gridLayout.addWidget(self.btn_scaleOnly, 2, 0, 1, 1)
        self.btn_userSetup = QtWidgets.QPushButton(mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_userSetup.sizePolicy().hasHeightForWidth())
        self.btn_userSetup.setSizePolicy(sizePolicy)
        self.btn_userSetup.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_userSetup.setFont(font)
        self.btn_userSetup.setObjectName("btn_userSetup")
        self.gridLayout.addWidget(self.btn_userSetup, 2, 1, 1, 1)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "mainMenu"))
        self.lbl_title.setText(_translate("mainMenu", "IoT Smart Scale"))
        self.btn_update.setText(_translate("mainMenu", "System Update"))
        self.btn_close.setText(_translate("mainMenu", "Close"))
        self.btn_login.setText(_translate("mainMenu", "Login"))
        self.btn_guest.setText(_translate("mainMenu", "Guest"))
        self.btn_scaleOnly.setText(_translate("mainMenu", "Scale Only"))
        self.btn_userSetup.setText(_translate("mainMenu", "User Setup"))

