# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editprofile.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editProfile(object):
    def setupUi(self, editProfile):
        editProfile.setObjectName("editProfile")
        editProfile.resize(800, 480)
        self.gridLayout = QtWidgets.QGridLayout(editProfile)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_title = QtWidgets.QLabel(editProfile)
        self.lbl_title.setMinimumSize(QtCore.QSize(121, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout.addWidget(self.lbl_title, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(editProfile)
        self.groupBox.setMinimumSize(QtCore.QSize(741, 331))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_name.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_name)
        self.lineEdit_name = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.lbl_email = QtWidgets.QLabel(self.groupBox)
        self.lbl_email.setMinimumSize(QtCore.QSize(35, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_email.setFont(font)
        self.lbl_email.setObjectName("lbl_email")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_email)
        self.lineEdit_email = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(513, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_email)
        self.lbl_gender = QtWidgets.QLabel(self.groupBox)
        self.lbl_gender.setMinimumSize(QtCore.QSize(61, 19))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gender.setFont(font)
        self.lbl_gender.setObjectName("lbl_gender")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_gender)
        self.comboBox_gender = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_gender.setMinimumSize(QtCore.QSize(519, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.comboBox_gender.setFont(font)
        self.comboBox_gender.setEditable(False)
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_gender)
        self.lbl_birthYear = QtWidgets.QLabel(self.groupBox)
        self.lbl_birthYear.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_birthYear.setFont(font)
        self.lbl_birthYear.setObjectName("lbl_birthYear")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_birthYear)
        self.spinBox_birthYear = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_birthYear.setMinimumSize(QtCore.QSize(513, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.spinBox_birthYear.setFont(font)
        self.spinBox_birthYear.setMinimum(1890)
        self.spinBox_birthYear.setMaximum(2017)
        self.spinBox_birthYear.setProperty("value", 1890)
        self.spinBox_birthYear.setObjectName("spinBox_birthYear")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_birthYear)
        self.lbl_height = QtWidgets.QLabel(self.groupBox)
        self.lbl_height.setMinimumSize(QtCore.QSize(55, 19))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_height.setFont(font)
        self.lbl_height.setObjectName("lbl_height")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_height)
        self.lineEdit_height = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_height.setMinimumSize(QtCore.QSize(513, 19))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_height.setFont(font)
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_height)
        self.comboBox_height = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_height.setMinimumSize(QtCore.QSize(519, 26))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.comboBox_height.setFont(font)
        self.comboBox_height.setEditable(False)
        self.comboBox_height.setObjectName("comboBox_height")
        self.comboBox_height.addItem("")
        self.comboBox_height.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_height)
        self.lbl_weight = QtWidgets.QLabel(self.groupBox)
        self.lbl_weight.setMinimumSize(QtCore.QSize(57, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_weight.setFont(font)
        self.lbl_weight.setObjectName("lbl_weight")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_weight)
        self.lineEdit_weight = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_weight.setMinimumSize(QtCore.QSize(513, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_weight.setFont(font)
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_weight)
        self.comboBox_weight = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_weight.setMinimumSize(QtCore.QSize(519, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.comboBox_weight.setFont(font)
        self.comboBox_weight.setEditable(False)
        self.comboBox_weight.setObjectName("comboBox_weight")
        self.comboBox_weight.addItem("")
        self.comboBox_weight.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_weight)
        self.lbl_passcode = QtWidgets.QLabel(self.groupBox)
        self.lbl_passcode.setMinimumSize(QtCore.QSize(35, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_passcode.setFont(font)
        self.lbl_passcode.setObjectName("lbl_passcode")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_passcode)
        self.comboBox_passcode = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_passcode.setMinimumSize(QtCore.QSize(519, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.comboBox_passcode.setFont(font)
        self.comboBox_passcode.setEditable(False)
        self.comboBox_passcode.setObjectName("comboBox_passcode")
        self.comboBox_passcode.addItem("")
        self.comboBox_passcode.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_passcode)
        self.lbl_fingerprint = QtWidgets.QLabel(self.groupBox)
        self.lbl_fingerprint.setMinimumSize(QtCore.QSize(103, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fingerprint.setFont(font)
        self.lbl_fingerprint.setObjectName("lbl_fingerprint")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_fingerprint)
        self.comboBox_fingerprint = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_fingerprint.setMinimumSize(QtCore.QSize(519, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.comboBox_fingerprint.setFont(font)
        self.comboBox_fingerprint.setEditable(False)
        self.comboBox_fingerprint.setObjectName("comboBox_fingerprint")
        self.comboBox_fingerprint.addItem("")
        self.comboBox_fingerprint.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_fingerprint)
        self.checkBox_rememberMe = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_rememberMe.setFont(font)
        self.checkBox_rememberMe.setObjectName("checkBox_rememberMe")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkBox_rememberMe)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 3)
        self.btn_back_2 = QtWidgets.QPushButton(editProfile)
        self.btn_back_2.setMinimumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_back_2.setFont(font)
        self.btn_back_2.setObjectName("btn_back_2")
        self.gridLayout.addWidget(self.btn_back_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(487, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.btn_back = QtWidgets.QPushButton(editProfile)
        self.btn_back.setMinimumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 2, 2, 1, 1)

        self.retranslateUi(editProfile)
        QtCore.QMetaObject.connectSlotsByName(editProfile)

    def retranslateUi(self, editProfile):
        _translate = QtCore.QCoreApplication.translate
        editProfile.setWindowTitle(_translate("editProfile", "editProfile"))
        self.lbl_title.setText(_translate("editProfile", "Edit Profile"))
        self.lbl_name.setText(_translate("editProfile", "Name:"))
        self.lbl_email.setText(_translate("editProfile", "Email:"))
        self.lbl_gender.setText(_translate("editProfile", "Gender:"))
        self.comboBox_gender.setCurrentText(_translate("editProfile", "Female"))
        self.comboBox_gender.setItemText(0, _translate("editProfile", "Female"))
        self.comboBox_gender.setItemText(1, _translate("editProfile", "Male"))
        self.lbl_birthYear.setText(_translate("editProfile", "Birth Year:"))
        self.lbl_height.setText(_translate("editProfile", "Height:"))
        self.comboBox_height.setCurrentText(_translate("editProfile", "cm"))
        self.comboBox_height.setItemText(0, _translate("editProfile", "cm"))
        self.comboBox_height.setItemText(1, _translate("editProfile", "in"))
        self.lbl_weight.setText(_translate("editProfile", "Weight:"))
        self.comboBox_weight.setCurrentText(_translate("editProfile", "kg"))
        self.comboBox_weight.setItemText(0, _translate("editProfile", "kg"))
        self.comboBox_weight.setItemText(1, _translate("editProfile", "lb"))
        self.lbl_passcode.setText(_translate("editProfile", "Passcode:"))
        self.comboBox_passcode.setCurrentText(_translate("editProfile", "Enabled"))
        self.comboBox_passcode.setItemText(0, _translate("editProfile", "Enabled"))
        self.comboBox_passcode.setItemText(1, _translate("editProfile", "Disabled"))
        self.lbl_fingerprint.setText(_translate("editProfile", "Fingerprint Login:"))
        self.comboBox_fingerprint.setCurrentText(_translate("editProfile", "Enabled"))
        self.comboBox_fingerprint.setItemText(0, _translate("editProfile", "Enabled"))
        self.comboBox_fingerprint.setItemText(1, _translate("editProfile", "Disabled"))
        self.checkBox_rememberMe.setText(_translate("editProfile", "Remember Me"))
        self.btn_back_2.setText(_translate("editProfile", "Back"))
        self.btn_back.setText(_translate("editProfile", "Done"))

