# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scaleonly.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_scaleOnly(object):
    def setupUi(self, scaleOnly):
        scaleOnly.setObjectName("scaleOnly")
        scaleOnly.resize(800, 480)
        self.gridLayout = QtWidgets.QGridLayout(scaleOnly)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title = QtWidgets.QLabel(scaleOnly)
        self.lbl_title.setMinimumSize(QtCore.QSize(571, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_2.addWidget(self.lbl_title)
        self.lbl_instruction = QtWidgets.QLabel(scaleOnly)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.lbl_instruction.setFont(font)
        self.lbl_instruction.setObjectName("lbl_instruction")
        self.verticalLayout_2.addWidget(self.lbl_instruction)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 2, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(43, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.frame_lcd = QtWidgets.QFrame(scaleOnly)
        self.frame_lcd.setMinimumSize(QtCore.QSize(561, 151))
        self.frame_lcd.setMaximumSize(QtCore.QSize(561, 151))
        self.frame_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lcd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lcd.setObjectName("frame_lcd")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_lcd)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcd_number = QtWidgets.QLCDNumber(self.frame_lcd)
        self.lcd_number.setMinimumSize(QtCore.QSize(501, 121))
        self.lcd_number.setMaximumSize(QtCore.QSize(501, 121))
        self.lcd_number.setObjectName("lcd_number")
        self.horizontalLayout.addWidget(self.lcd_number)
        self.lbl_g = QtWidgets.QLabel(self.frame_lcd)
        self.lbl_g.setMinimumSize(QtCore.QSize(31, 71))
        self.lbl_g.setMaximumSize(QtCore.QSize(31, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_g.setFont(font)
        self.lbl_g.setObjectName("lbl_g")
        self.horizontalLayout.addWidget(self.lbl_g)
        self.horizontalLayout_2.addWidget(self.frame_lcd)
        spacerItem2 = QtWidgets.QSpacerItem(43, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(17, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_back = QtWidgets.QPushButton(scaleOnly)
        self.btn_back.setMinimumSize(QtCore.QSize(151, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back)
        spacerItem5 = QtWidgets.QSpacerItem(232, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.btn_tare = QtWidgets.QPushButton(scaleOnly)
        self.btn_tare.setMinimumSize(QtCore.QSize(151, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.btn_tare.setFont(font)
        self.btn_tare.setObjectName("btn_tare")
        self.horizontalLayout_3.addWidget(self.btn_tare)
        spacerItem6 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 2)

        self.retranslateUi(scaleOnly)
        QtCore.QMetaObject.connectSlotsByName(scaleOnly)

    def retranslateUi(self, scaleOnly):
        _translate = QtCore.QCoreApplication.translate
        scaleOnly.setWindowTitle(_translate("scaleOnly", "scaleOnly"))
        self.lbl_title.setText(_translate("scaleOnly", "Scale Only"))
        self.lbl_instruction.setText(_translate("scaleOnly", "Please place food item on scale. You may leave the door open."))
        self.lbl_g.setText(_translate("scaleOnly", "g"))
        self.btn_back.setText(_translate("scaleOnly", "Back"))
        self.btn_tare.setText(_translate("scaleOnly", "Tare"))

